In [2]:
s

In [3]:
import pandas as pd

In [4]:
df = pd.DataFrame(people)

In [5]:
df

   first     last            email
0  Corey  Schafer  Corey@gmail.com
1   Jane      Doe   Jane@gmail.com
2   John      Doe   John@yahoo.com

In [24]:
df

                 first     last
email
Corey@gmail.com  Corey  Schafer
Jane@gmail.com    Jane      Doe
John@yahoo.com    John      Doe

In [6]:
df.set_index("email")

                 first     last
email
Corey@gmail.com  Corey  Schafer
Jane@gmail.com    Jane      Doe
John@yahoo.com    John      Doe

In [7]:
df.index

RangeIndex(start=0, stop=3, step=1)

In [9]:
df.loc["Corey@gmail.com","last"]

KeyError: 'Corey@gmail.com'

In [10]:
df.iloc[0]

first              Corey
last             Schafer
email    Corey@gmail.com
Name: 0, dtype: object

In [11]:
df.reset_index(inplace= True)

In [47]:
df = pd.read_csv("data/survey_results_public.csv",index_col = "ResponseId")
schema_df = pd.read_csv("data/survey_results_schema.csv",index_col = "qname")

In [44]:
pd.set_option("display.max_columns",df.shape[1])
pd.set_option("display.max_rows",df.shape[0])

In [38]:
df.head()

,MainBranch,Age,Employment,RemoteWork,Check,CodingActivities,EdLevel,LearnCode,LearnCodeOnline,TechDoc,YearsCode,YearsCodePro,DevType,OrgSize,PurchaseInfluence,BuyNewTool,BuildvsBuy,TechEndorse,Country,Currency,CompTotal,LanguageHaveWorkedWith,LanguageWantToWorkWith,LanguageAdmired,DatabaseHaveWorkedWith,DatabaseWantToWorkWith,DatabaseAdmired,PlatformHaveWorkedWith,PlatformWantToWorkWith,PlatformAdmired,WebframeHaveWorkedWith,WebframeWantToWorkWith,WebframeAdmired,EmbeddedHaveWorkedWith,EmbeddedWantToWorkWith,EmbeddedAdmired,MiscTechHaveWorkedWith,MiscTechWantToWorkWith,MiscTechAdmired,ToolsTechHaveWorkedWith,ToolsTechWantToWorkWith,ToolsTechAdmired,...,AINextNo change,AINextMore integrated,AINextLess integrated,AINextMuch less integrated,AIThreat,AIEthics,AIChallenges,TBranch,ICorPM,WorkExp,Knowledge_1,Knowledge_2,Knowledge_3,Knowledge_4,Knowledge_5,Knowledge_6,Knowledge_7,Knowledge_8,Knowledge_9,Frequency_1,Frequency_2,Frequency_3,TimeSearching,TimeAnswering,Frustration,ProfessionalTech,ProfessionalCloud,ProfessionalQuestion,Industry,JobSatPoints_1,JobSatPoints_4,JobSatPoints_5,JobSatPoints_6,JobSatPoints_7,JobSatPoints_8,JobSatPoints_9,JobSatPoints_10,JobSatPoints_11,SurveyLength,SurveyEase,ConvertedCompYearly,JobSat
ResponseId,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,
1,I am a developer by profession,Under 18 years old,"Employed, full-time",Remote,Apples,Hobby,Primary/elementary school,Books / Physical media,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,United States of America,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,No,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,I am a developer by profession,35-44 years old,"Employed, full-time",Remote,Apples,Hobby;Contribute to open-source projects;Other...,"Bachelor’s degree (B.A., B.S., B.Eng., etc.)",Books / Physical media;Colleague;On the job tr...,Technical documentation;Blogs;Books;Written Tu...,API document(s) and/or SDK document(s);User gu...,20,17,"Developer, full-stack",NaN,NaN,NaN,NaN,NaN,United Kingdom of Great Britain and Northern I...,NaN,NaN,Bash/Shell (all shells);Go;HTML/CSS;Java;JavaS...,Bash/Shell (all shells);Go;HTML/CSS;Java;JavaS...,Bash/Shell (all shells);Go;HTML/CSS;Java;JavaS...,Dynamodb;MongoDB;PostgreSQL,PostgreSQL,PostgreSQL,Amazon Web Services (AWS);Heroku;Netlify,Amazon Web Services (AWS);Heroku;Netlify,Amazon Web Services (AWS);Heroku;Netlify,Express;Next.js;Node.js;React,Express;Htmx;Node.js;React;Remix,Express;Node.js;React,NaN,NaN,NaN,NaN,NaN,NaN,Docker;Homebrew;Kubernetes;npm;Vite;Webpack,Docker;Homebrew;Kubernetes;npm;Vite;Webpack,Docker;Homebrew;Kubernetes;npm;Vite;Webpack,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Yes,Individual contributor,17.0,Agree,Disagree,Agree,Agree,Agree,Neither agree nor disagree,Disagree,Agree,Agree,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,NaN,NaN,NaN,NaN
3,I am a developer by profession,45-54 years old,"Employed, full-time",Remote,Apples,Hobby;Contribute to open-source projects;Other...,"Master’s degree (M.A., M.S., M.Eng., MBA, etc.)",Books / Physical media;Colleague;On the job tr...,Technical documentation;Blogs;Books;Written Tu...,API document(s) and/or SDK document(s);User gu...,37,27,Developer Experience,NaN,NaN,NaN,NaN,NaN,United Kingdom of Great Britain and Northern I...,NaN,NaN,C#,C#,C#,Firebase Realtime Database,Firebase Realtime Database,Firebase Realtime Database,Google Cloud,Google Cloud,Google Cloud,ASP.NET CORE,ASP.NET CORE,ASP.NET CORE,Rasberry Pi,Rasberry Pi,Rasberry Pi,.NET (5+) ;.NET Framework (1.0 - 4.8);.NET MAUI,.NET (5+) ;.NET Framework (1.0 - 4.8);.NET MAUI,.NET (5+) ;.NET Framework (1.0 - 4.8);.NET MAUI,MSBuild,MSBuild,MSBuild,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,No,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Appropriate in length,Easy,NaN,NaN
4,I am learning to code,18-24 years old,"Student, full-time",NaN,Apples,NaN,Some college/university study without earning ...,"Other online resources (e.g., videos, blogs, f...",Stack Overflow;How-to videos;Interactive tutorial,NaN,4,NaN,"Developer, full-stack",NaN,NaN,NaN,NaN,NaN,Canada,NaN,NaN,C;C++;HTML/CSS;Java;JavaScript;PHP;PowerShell;...,HTML/CSS;Java;JavaScript;PowerShell;Python;SQL...,HTML/CSS;Java;JavaScript;PowerShell;Python;SQL...,MongoDB;MySQL;PostgreSQL;SQLite,MongoDB;MySQL;PostgreSQL,MongoDB;MySQL;PostgreSQL,Amazon Web Services (AWS);Fly.io;Heroku,Amazon Web Services (AWS);Vercel,Amazon Web Services (AWS),jQuery;Next.js;Node.js;React;WordPress,jQuery;Next.js;Node.js;React,jQuery;Next.js;Node.js;React,Rasberry Pi,NaN,NaN,NumPy;Pandas;Ruff;TensorFlow,NaN,NaN,Docker;npm;Pip,Docker;Kubernetes;npm,Docker;npm,...,NaN,NaN,NaN,NaN,No,Circulating misinformation or disinformation;M...,Don’t trust the output or answers,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Too long,Easy,NaN,NaN
5,I am a developer by profession,18-24 years old,"Student, full-time",NaN,Apples,NaN,"Secondary school (e.g. American high school, G...","Other online resources (e.g., videos, blogs, f...",Technical documentation;Blogs;Written Tutorial...,API document(s) and/or SDK document(s);User gu...,9,NaN,"Developer, full-stack",NaN,NaN,NaN,NaN,NaN,Norway,NaN,NaN,C++;HTML/CSS;JavaScript;Lua;Python;Rust,C++;HTML/CSS;JavaScript;Lua;Python,C++;HTML/CSS;JavaScript;Lua;Python,PostgreSQL;SQLite,PostgreSQL;SQLite,PostgreSQL;SQLite,NaN,NaN,NaN,NaN,NaN,NaN,CMake;Cargo;Rasberry Pi,CMake;Rasberry Pi,CMake;Rasberry Pi,NaN,NaN,NaN,APT;Make;npm,APT;Make,APT;Make,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Too short,Easy,NaN,NaN

In [42]:
df.loc[1]

MainBranch             I am a developer by profession
Age                                Under 18 years old
Employment                        Employed, full-time
RemoteWork                                     Remote
Check                                          Apples
                                    ...
JobSatPoints_11                                   NaN
SurveyLength                                      NaN
SurveyEase                                        NaN
ConvertedCompYearly                               NaN
JobSat                                            NaN
Name: 1, Length: 113, dtype: object

In [45]:
schema_df

,qid,qname,question,force_resp,type,selector
0,QID2,MainBranch,Which of the following options best describes ...,True,MC,SAVR
1,QID127,Age,What is your age?*,True,MC,SAVR
2,QID296,Employment,Which of the following best describes your cur...,True,MC,MAVR
3,QID308,RemoteWork,Which best describes your current work situation?,False,MC,SAVR
4,QID341,Check,Just checking to make sure you are paying atte...,True,MC,SAVR
5,QID297,CodingActivities,Which of the following best describes the code...,False,MC,MAVR
6,QID25,EdLevel,Which of the following best describes the high...,True,MC,SAVR
7,QID276,LearnCode,How do you learn to code? Select all that apply.,False,MC,MAVR
8,QID281,LearnCodeOnline,What online resources do you use to learn to c...,False,MC,MAVR
9,QID331,TechDoc,What is the source of the technical documentat...,False,MC,MAVR
10,QID32,YearsCode,"Including any education, how many years have y...",False,MC,DL
11,QID34,YearsCodePro,"NOT including education, how many years have y...",False,MC,DL
12,QID31,DevType,Which of the following describes your current ...,False,MC,SAVR
13,QID29,OrgSize,Approximately how many people are employed by ...,False,MC,SAVR
14,QID278,PurchaseInfluence,"What level of influence do you, personally, ha...",False,MC,SAVR
15,QID279,BuyNewTool,"When buying a new tool or software, how do you...",False,MC,MAVR
16,QID330,BuildvsBuy,When asked to provide a recommendation for sol...,False,MC,SAVR
17,QID335,TechEndorse,What product feature do you care about most wh...,False,MC,MAVR
18,QID6,Country,"Where do you live? <span style=""font-weight: b...",True,MC,DL
19,QID50,Currency,Which currency do you use day-to-day? If your ...,True,MC,DL
20,QID51,CompTotal,What is your current total <b>annual</b> compe...,False,TE,SL
21,QID233,Language,"Which <b>programming, scripting, and markup la...",False,Matrix,Likert
22,QID262,Database,Which <b>database environments </b>have you do...,False,Matrix,Likert
23,QID263,Platform,Which <b>cloud platforms</b> have you done ext...,False,Matrix,Likert
24,QID264,Webframe,Which <b>web frameworks and web technologies</...,False,Matrix,Likert
25,QID340,Embedded,Which <b>embedded systems and technologies</b>...,False,Matrix,Likert
26,QID265,MiscTech,Which <b>other frameworks and libraries</b> ha...,False,Matrix,Likert
27,QID275,ToolsTech,Which <b>developer </b><strong>tools for compi...,False,Matrix,Likert
28,QID274,NEWCollabTools,Which <strong>development environments</strong...,False,Matrix,Likert
29,QID71,OpSys,What is the primary <b>operating system</b> in...,False,Matrix,Likert
30,QID282,OfficeStackAsync,Which <b>collaborative work management and/or ...,False,Matrix,Likert
31,QID307,OfficeStackSync,Which <b>communication tools</b> did you use r...,False,Matrix,Likert
32,QID327,AISearchDev,Which <b>AI-powered search and developer tools...,False,Matrix,Likert
33,QID266,NEWSOSites,Which of the following Stack Overflow sites ha...,True,MC,MAVR
34,QID100,SOVisitFreq,How frequently would you say you visit Stack O...,False,MC,SAVR
35,QID101,SOAccount,Do you have a Stack Overflow account?,False,MC,SAVR
36,QID102,SOPartFreq,How frequently would you say you participate i...,False,MC,SAVR
37,QID334,SOHow,How do you use Stack Overflow? Select all tha...,False,MC,MAVR
38,QID106,SOComm,Do you consider yourself a member of the Stack...,False,MC,SAVR
39,QID314,AISelect,Do you currently use AI tools in your developm...,True,MC,SAVR
40,QID315,AISent,How favorable is your stance on using AI tools...,False,MC,SAVR
41,QID324,AIBen,For the AI tools you use as part of your devel...,False,MC,MAVR
42,QID316,AIAcc,How much do you trust the accuracy of the outp...,False,MC,SAVR
43,QID343,AIComplex,How well do the AI tools you use in your devel...,False,MC,SAVR
44,QID319,AITool,Which parts of your development workflow are y...,False,Matrix,Likert
45,QID320,AINext,Thinking about how your job and process change...,False,Matrix,Likert
46,QID338,AIThreat,Do you believe AI is a threat to your current ...,False,MC,SAVR
47,QID339,AIEthics,Which AI ethical responsibilities are most imp...,False,MC,MAVR
48,QID346,AIChallenges,What are the challenges to your company/whole ...,False,MC,MAVR
49,QID299,TBranch,"<span style=""font-size:16px;"">Would you like t...",True,MC,SAVR
50,QID287,ICorPM,Are you an individual contributor or people ma...,False,MC,SAVR
51,QID288,WorkExp,How many years of working experience do you have?,False,Slider,HSLIDER
52,QID289,Knowledge,Please rate your level of agreement with the f...,False,Matrix,Likert
53,QID290,Frequency,How frequently do you experience each of the f...,False,Matrix,Likert
54,QID291,TimeSearching,"On an average day, how much time do you typica...",False,MC,SAVR
55,QID292,TimeAnswering,"On an average day, how much time do you typica...",False,MC,SAVR
56,QID342,Frustration,Which of these company challenges causes you t...,False,MC,MAVR
57,QID304,ProfessionalTech,My company has:,False,MC,MAVR
58,QID332,ProfessionalCloud,"At my company, our applications, databases and...",False,MC,SAVR
59,QID333,ProfessionalQuestion,"When you have a technical question at work, wh...",False,MC,SAVR
60,QID326,Industry,What industry is the company you work for in?,False,MC,SAVR
61,QID336,JobSat,How satisfied are you in your current professi...,False,MC,NPS
62,QID337,JobSatPoints,Assign points to the following attributes of y...,False,CS,VRTL
63,QID286,SOTeamsUsage,Does your team use Stack Overflow for Teams?,False,MC,SAVR
64,QID132,SurveyLength,How do you feel about the length of the survey...,False,MC,MAVR
65,QID133,SurveyEase,How easy or difficult was this survey to compl...,False,MC,MAVR
66,QID289,Knowledge_1,I have interactions with people outside of my ...,NaN,MC,MAVR
67,QID289,Knowledge_2,Knowledge silos prevent me from getting ideas ...,NaN,MC,MAVR
68,QID289,Knowledge_3,I can find up-to-date information within my or...,NaN,MC,MAVR
69,QID289,Knowledge_4,I am able to quickly find answers to my questi...,NaN,MC,MAVR
70,QID289,Knowledge_5,I know which system or resource to use to find...,NaN,MC,MAVR
71,QID289,Knowledge_6,I often find myself answering questions that I...,NaN,MC,MAVR
72,QID289,Knowledge_7,Waiting on answers to questions often causes i...,NaN,MC,MAVR
73,QID289,Knowledge_8,I feel like I have the tools and/or resources ...,NaN,MC,MAVR
74,QID289,Knowledge_9,I have asked my employer to reimburse me for t...,NaN,MC,MAVR
75,QID290,Frequency_1,Needing help from people outside of your immed...,NaN,MC,MAVR
76,QID290,Frequency_2,Interacting with people outside of your immedi...,NaN,MC,MAVR
77,QID290,Frequency_3,Encountering knowledge silos (where one indivi...,NaN,MC,MAVR
78,QID337,JobSatPoints_1,Driving strategy for my team,NaN,MC,MAVR
79,QID337,JobSatPoints_4,Contributing to open source,NaN,MC,MAVR
80,QID337,JobSatPoints_5,Securing data and environments,NaN,MC,MAVR
81,QID337,JobSatPoints_6,Improving quality of code and developer enviro...,NaN,MC,MAVR
82,QID337,JobSatPoints_7,"Learning and using new technology, including p...",NaN,MC,MAVR
83,QID337,JobSatPoints_8,"Designing and building environments, databases...",NaN,MC,MAVR
84,QID337,JobSatPoints_9,"Being a power user of a tool, developer langua...",NaN,MC,MAVR
85,QID337,JobSatPoints_10,Working with new and/or top-quality hardware,NaN,MC,MAVR
86,QID337,JobSatPoints_11,A well-staffed/sourced internal network that m...,NaN,MC,MAVR

In [57]:
schema_df.loc["TechDoc"]["question"]

'What is the source of the technical documentation you use most often to learn to code?  Select all that apply.'

In [59]:
schema_df.sort_index(ascending = False)

,qid,question,force_resp,type,selector
qname,,,,,
YearsCodePro,QID34,"NOT including education, how many years have y...",False,MC,DL
YearsCode,QID32,"Including any education, how many years have y...",False,MC,DL
WorkExp,QID288,How many years of working experience do you have?,False,Slider,HSLIDER
Webframe,QID264,Which <b>web frameworks and web technologies</...,False,Matrix,Likert
ToolsTech,QID275,Which <b>developer </b><strong>tools for compi...,False,Matrix,Likert
TimeSearching,QID291,"On an average day, how much time do you typica...",False,MC,SAVR
TimeAnswering,QID292,"On an average day, how much time do you typica...",False,MC,SAVR
TechEndorse,QID335,What product feature do you care about most wh...,False,MC,MAVR
TechDoc,QID331,What is the source of the technical documentat...,False,MC,MAVR
TBranch,QID299,"<span style=""font-size:16px;"">Would you like t...",True,MC,SAVR
SurveyLength,QID132,How do you feel about the length of the survey...,False,MC,MAVR
SurveyEase,QID133,How easy or difficult was this survey to compl...,False,MC,MAVR
SOVisitFreq,QID100,How frequently would you say you visit Stack O...,False,MC,SAVR
SOTeamsUsage,QID286,Does your team use Stack Overflow for Teams?,False,MC,SAVR
SOPartFreq,QID102,How frequently would you say you participate i...,False,MC,SAVR
SOHow,QID334,How do you use Stack Overflow? Select all tha...,False,MC,MAVR
SOComm,QID106,Do you consider yourself a member of the Stack...,False,MC,SAVR
SOAccount,QID101,Do you have a Stack Overflow account?,False,MC,SAVR
RemoteWork,QID308,Which best describes your current work situation?,False,MC,SAVR
PurchaseInfluence,QID278,"What level of influence do you, personally, ha...",False,MC,SAVR
ProfessionalTech,QID304,My company has:,False,MC,MAVR
ProfessionalQuestion,QID333,"When you have a technical question at work, wh...",False,MC,SAVR
ProfessionalCloud,QID332,"At my company, our applications, databases and...",False,MC,SAVR
Platform,QID263,Which <b>cloud platforms</b> have you done ext...,False,Matrix,Likert
OrgSize,QID29,Approximately how many people are employed by ...,False,MC,SAVR
OpSys,QID71,What is the primary <b>operating system</b> in...,False,Matrix,Likert
OfficeStackSync,QID307,Which <b>communication tools</b> did you use r...,False,Matrix,Likert
OfficeStackAsync,QID282,Which <b>collaborative work management and/or ...,False,Matrix,Likert
NEWSOSites,QID266,Which of the following Stack Overflow sites ha...,True,MC,MAVR
NEWCollabTools,QID274,Which <strong>development environments</strong...,False,Matrix,Likert
MiscTech,QID265,Which <b>other frameworks and libraries</b> ha...,False,Matrix,Likert
MainBranch,QID2,Which of the following options best describes ...,True,MC,SAVR
LearnCodeOnline,QID281,What online resources do you use to learn to c...,False,MC,MAVR
LearnCode,QID276,How do you learn to code? Select all that apply.,False,MC,MAVR
Language,QID233,"Which <b>programming, scripting, and markup la...",False,Matrix,Likert
Knowledge_9,QID289,I have asked my employer to reimburse me for t...,NaN,MC,MAVR
Knowledge_8,QID289,I feel like I have the tools and/or resources ...,NaN,MC,MAVR
Knowledge_7,QID289,Waiting on answers to questions often causes i...,NaN,MC,MAVR
Knowledge_6,QID289,I often find myself answering questions that I...,NaN,MC,MAVR
Knowledge_5,QID289,I know which system or resource to use to find...,NaN,MC,MAVR
Knowledge_4,QID289,I am able to quickly find answers to my questi...,NaN,MC,MAVR
Knowledge_3,QID289,I can find up-to-date information within my or...,NaN,MC,MAVR
Knowledge_2,QID289,Knowledge silos prevent me from getting ideas ...,NaN,MC,MAVR
Knowledge_1,QID289,I have interactions with people outside of my ...,NaN,MC,MAVR
Knowledge,QID289,Please rate your level of agreement with the f...,False,Matrix,Likert
JobSatPoints_9,QID337,"Being a power user of a tool, developer langua...",NaN,MC,MAVR
JobSatPoints_8,QID337,"Designing and building environments, databases...",NaN,MC,MAVR
JobSatPoints_7,QID337,"Learning and using new technology, including p...",NaN,MC,MAVR
JobSatPoints_6,QID337,Improving quality of code and developer enviro...,NaN,MC,MAVR
JobSatPoints_5,QID337,Securing data and environments,NaN,MC,MAVR
JobSatPoints_4,QID337,Contributing to open source,NaN,MC,MAVR
JobSatPoints_11,QID337,A well-staffed/sourced internal network that m...,NaN,MC,MAVR
JobSatPoints_10,QID337,Working with new and/or top-quality hardware,NaN,MC,MAVR
JobSatPoints_1,QID337,Driving strategy for my team,NaN,MC,MAVR
JobSatPoints,QID337,Assign points to the following attributes of y...,False,CS,VRTL
JobSat,QID336,How satisfied are you in your current professi...,False,MC,NPS
Industry,QID326,What industry is the company you work for in?,False,MC,SAVR
ICorPM,QID287,Are you an individual contributor or people ma...,False,MC,SAVR
Frustration,QID342,Which of these company challenges causes you t...,False,MC,MAVR
Frequency_3,QID290,Encountering knowledge silos (where one indivi...,NaN,MC,MAVR
Frequency_2,QID290,Interacting with people outside of your immedi...,NaN,MC,MAVR
Frequency_1,QID290,Needing help from people outside of your immed...,NaN,MC,MAVR
Frequency,QID290,How frequently do you experience each of the f...,False,Matrix,Likert
Employment,QID296,Which of the following best describes your cur...,True,MC,MAVR
Embedded,QID340,Which <b>embedded systems and technologies</b>...,False,Matrix,Likert
EdLevel,QID25,Which of the following best describes the high...,True,MC,SAVR
DevType,QID31,Which of the following describes your current ...,False,MC,SAVR
Database,QID262,Which <b>database environments </b>have you do...,False,Matrix,Likert
Currency,QID50,Which currency do you use day-to-day? If your ...,True,MC,DL
Country,QID6,"Where do you live? <span style=""font-weight: b...",True,MC,DL
CompTotal,QID51,What is your current total <b>annual</b> compe...,False,TE,SL
CodingActivities,QID297,Which of the following best describes the code...,False,MC,MAVR
Check,QID341,Just checking to make sure you are paying atte...,True,MC,SAVR
BuyNewTool,QID279,"When buying a new tool or software, how do you...",False,MC,MAVR
BuildvsBuy,QID330,When asked to provide a recommendation for sol...,False,MC,SAVR
Age,QID127,What is your age?*,True,MC,SAVR
AITool,QID319,Which parts of your development workflow are y...,False,Matrix,Likert
AIThreat,QID338,Do you believe AI is a threat to your current ...,False,MC,SAVR
AISent,QID315,How favorable is your stance on using AI tools...,False,MC,SAVR
AISelect,QID314,Do you currently use AI tools in your developm...,True,MC,SAVR
AISearchDev,QID327,Which <b>AI-powered search and developer tools...,False,Matrix,Likert
AINext,QID320,Thinking about how your job and process change...,False,Matrix,Likert
AIEthics,QID339,Which AI ethical responsibilities are most imp...,False,MC,MAVR
AIComplex,QID343,How well do the AI tools you use in your devel...,False,MC,SAVR
AIChallenges,QID346,What are the challenges to your company/whole ...,False,MC,MAVR
AIBen,QID324,For the AI tools you use as part of your devel...,False,MC,MAVR
AIAcc,QID316,How much do you trust the accuracy of the outp...,False,MC,SAVR