In [21]:
people = {
    "first" : ["Corey","Jane","John"],
    "last"  : ["Schafer","Doe","Doe"],
    "email" : ["Corey@gmail.com","Jane@gmail.com","John@yahoo.com"]
}

In [22]:
import pandas as pd

In [23]:
df = pd.DataFrame(people)

In [24]:
df

   first     last            email
0  Corey  Schafer  Corey@gmail.com
1   Jane      Doe   Jane@gmail.com
2   John      Doe   John@yahoo.com

In [25]:
# adding removing columns:

df["first"] +" "+ df["last"]

0    Corey Schafer
1         Jane Doe
2         John Doe
dtype: object

In [26]:
df["full_name"] = df["first"] +" "+ df["last"]

In [27]:
df

   first     last            email      full_name
0  Corey  Schafer  Corey@gmail.com  Corey Schafer
1   Jane      Doe   Jane@gmail.com       Jane Doe
2   John      Doe   John@yahoo.com       John Doe

In [30]:
df.drop(columns = ["first","last"],inplace = True)

In [31]:
df

             email      full_name
0  Corey@gmail.com  Corey Schafer
1   Jane@gmail.com       Jane Doe
2   John@yahoo.com       John Doe

In [33]:
df["full_name"].str.split(" ",expand = True)

       0        1
0  Corey  Schafer
1   Jane      Doe
2   John      Doe

In [34]:
df[["first","last"]] = df["full_name"].str.split(" ",expand = True)

In [35]:
df

             email      full_name  first     last
0  Corey@gmail.com  Corey Schafer  Corey  Schafer
1   Jane@gmail.com       Jane Doe   Jane      Doe
2   John@yahoo.com       John Doe   John      Doe

In [44]:
# adding and removing in rows
pd.concat([df, pd.DataFrame([{"first": "Tony","last":"stark"},
                             {"first" : "Jose"}])], ignore_index=True)

             email      full_name  first     last
0  Corey@gmail.com  Corey Schafer  Corey  Schafer
1   Jane@gmail.com       Jane Doe   Jane      Doe
2   John@yahoo.com       John Doe   John      Doe
3              NaN            NaN   Tony    stark
4              NaN            NaN   Jose      NaN

In [45]:
people = {
    "first" : ["Toney","Steve"],
    "last"  : ["Stark","Roger"],
    "email" : ["IronMan@gmail.com","Cap@gmail.com"]
}
df2  = pd.DataFrame(people)

In [48]:
df = pd.concat([df,df2],ignore_index = True)

In [49]:
df

               email      full_name  first     last
0    Corey@gmail.com  Corey Schafer  Corey  Schafer
1     Jane@gmail.com       Jane Doe   Jane      Doe
2     John@yahoo.com       John Doe   John      Doe
3  IronMan@gmail.com            NaN  Toney    Stark
4      Cap@gmail.com            NaN  Steve    Roger

In [52]:
df = df.drop(index = 4)

In [53]:
df

               email      full_name  first     last
0    Corey@gmail.com  Corey Schafer  Corey  Schafer
1     Jane@gmail.com       Jane Doe   Jane      Doe
2     John@yahoo.com       John Doe   John      Doe
3  IronMan@gmail.com            NaN  Toney    Stark

In [55]:
df.drop(index =df[df["last"] == "Doe"].index)

               email      full_name  first     last
0    Corey@gmail.com  Corey Schafer  Corey  Schafer
3  IronMan@gmail.com            NaN  Toney    Stark

In [56]:
# 14:15 (part6)