In [12]:
people = {
    "first" : ["Corey","Jane","John","Adam"],
    "last"  : ["Schafer","Doe","Doe","Doe"],
    "email" : ["Corey@gmail.com","Jane@gmail.com","John@yahoo.com","A@email.com"]
}

In [13]:
import pandas as pd

In [14]:
df = pd.DataFrame(people)

In [15]:
df

   first     last            email
0  Corey  Schafer  Corey@gmail.com
1   Jane      Doe   Jane@gmail.com
2   John      Doe   John@yahoo.com
3   Adam      Doe      A@email.com

In [16]:
# ***********************sorting

In [17]:
# sort by a columns
df.sort_values(by = "last",ascending = False)

   first     last            email
0  Corey  Schafer  Corey@gmail.com
1   Jane      Doe   Jane@gmail.com
2   John      Doe   John@yahoo.com
3   Adam      Doe      A@email.com

In [19]:

# the list argument will first deal with "last" and if the last names
# are same then it will consider the second list element ie "first"
df.sort_values(by = ["last","first"],ascending = False) # list of columns

   first     last            email
0  Corey  Schafer  Corey@gmail.com
2   John      Doe   John@yahoo.com
1   Jane      Doe   Jane@gmail.com
3   Adam      Doe      A@email.com

In [21]:
df.sort_values(by = ["last","first"],ascending = [False,True],inplace = True)

In [22]:
df

   first     last            email
0  Corey  Schafer  Corey@gmail.com
3   Adam      Doe      A@email.com
1   Jane      Doe   Jane@gmail.com
2   John      Doe   John@yahoo.com

In [25]:
df.sort_index(inplace = True)  # sorting by index

In [26]:
df

   first     last            email
0  Corey  Schafer  Corey@gmail.com
1   Jane      Doe   Jane@gmail.com
2   John      Doe   John@yahoo.com
3   Adam      Doe      A@email.com

In [27]:
df["last"].sort_values()

1        Doe
2        Doe
3        Doe
0    Schafer
Name: last, dtype: object

In [32]:
df = pd.read_csv("data/survey_results_public.csv",index_col = "ResponseId")
schema_df = pd.read_csv("data/survey_results_schema.csv")

In [33]:
pd.set_option("display.max_columns",None)
pd.set_option("display.max_rows",None)

In [34]:
df.head()

,MainBranch,Age,Employment,RemoteWork,Check,CodingActivities,EdLevel,LearnCode,LearnCodeOnline,TechDoc,YearsCode,YearsCodePro,DevType,OrgSize,PurchaseInfluence,BuyNewTool,BuildvsBuy,TechEndorse,Country,Currency,CompTotal,LanguageHaveWorkedWith,LanguageWantToWorkWith,LanguageAdmired,DatabaseHaveWorkedWith,DatabaseWantToWorkWith,DatabaseAdmired,PlatformHaveWorkedWith,PlatformWantToWorkWith,PlatformAdmired,WebframeHaveWorkedWith,WebframeWantToWorkWith,WebframeAdmired,EmbeddedHaveWorkedWith,EmbeddedWantToWorkWith,EmbeddedAdmired,MiscTechHaveWorkedWith,MiscTechWantToWorkWith,MiscTechAdmired,ToolsTechHaveWorkedWith,ToolsTechWantToWorkWith,ToolsTechAdmired,NEWCollabToolsHaveWorkedWith,NEWCollabToolsWantToWorkWith,NEWCollabToolsAdmired,OpSysPersonal use,OpSysProfessional use,OfficeStackAsyncHaveWorkedWith,OfficeStackAsyncWantToWorkWith,OfficeStackAsyncAdmired,OfficeStackSyncHaveWorkedWith,OfficeStackSyncWantToWorkWith,OfficeStackSyncAdmired,AISearchDevHaveWorkedWith,AISearchDevWantToWorkWith,AISearchDevAdmired,NEWSOSites,SOVisitFreq,SOAccount,SOPartFreq,SOHow,SOComm,AISelect,AISent,AIBen,AIAcc,AIComplex,AIToolCurrently Using,AIToolInterested in Using,AIToolNot interested in Using,AINextMuch more integrated,AINextNo change,AINextMore integrated,AINextLess integrated,AINextMuch less integrated,AIThreat,AIEthics,AIChallenges,TBranch,ICorPM,WorkExp,Knowledge_1,Knowledge_2,Knowledge_3,Knowledge_4,Knowledge_5,Knowledge_6,Knowledge_7,Knowledge_8,Knowledge_9,Frequency_1,Frequency_2,Frequency_3,TimeSearching,TimeAnswering,Frustration,ProfessionalTech,ProfessionalCloud,ProfessionalQuestion,Industry,JobSatPoints_1,JobSatPoints_4,JobSatPoints_5,JobSatPoints_6,JobSatPoints_7,JobSatPoints_8,JobSatPoints_9,JobSatPoints_10,JobSatPoints_11,SurveyLength,SurveyEase,ConvertedCompYearly,JobSat
ResponseId,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,
1,I am a developer by profession,Under 18 years old,"Employed, full-time",Remote,Apples,Hobby,Primary/elementary school,Books / Physical media,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,United States of America,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,I have never visited Stack Overflow or the Sta...,NaN,NaN,NaN,NaN,NaN,Yes,Very favorable,Increase productivity,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,No,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,I am a developer by profession,35-44 years old,"Employed, full-time",Remote,Apples,Hobby;Contribute to open-source projects;Other...,"Bachelor’s degree (B.A., B.S., B.Eng., etc.)",Books / Physical media;Colleague;On the job tr...,Technical documentation;Blogs;Books;Written Tu...,API document(s) and/or SDK document(s);User gu...,20,17,"Developer, full-stack",NaN,NaN,NaN,NaN,NaN,United Kingdom of Great Britain and Northern I...,NaN,NaN,Bash/Shell (all shells);Go;HTML/CSS;Java;JavaS...,Bash/Shell (all shells);Go;HTML/CSS;Java;JavaS...,Bash/Shell (all shells);Go;HTML/CSS;Java;JavaS...,Dynamodb;MongoDB;PostgreSQL,PostgreSQL,PostgreSQL,Amazon Web Services (AWS);Heroku;Netlify,Amazon Web Services (AWS);Heroku;Netlify,Amazon Web Services (AWS);Heroku;Netlify,Express;Next.js;Node.js;React,Express;Htmx;Node.js;React;Remix,Express;Node.js;React,NaN,NaN,NaN,NaN,NaN,NaN,Docker;Homebrew;Kubernetes;npm;Vite;Webpack,Docker;Homebrew;Kubernetes;npm;Vite;Webpack,Docker;Homebrew;Kubernetes;npm;Vite;Webpack,PyCharm;Visual Studio Code;WebStorm,PyCharm;Visual Studio Code;WebStorm,PyCharm;Visual Studio Code;WebStorm,MacOS;Windows,MacOS,NaN,NaN,NaN,Microsoft Teams;Slack,Slack,Slack,NaN,NaN,NaN,Stack Overflow for Teams (private knowledge sh...,Multiple times per day,Yes,Multiple times per day,Quickly finding code solutions;Finding reliabl...,"Yes, definitely","No, and I don't plan to",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Yes,Individual contributor,17.0,Agree,Disagree,Agree,Agree,Agree,Neither agree nor disagree,Disagree,Agree,Agree,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,NaN,NaN,NaN,NaN
3,I am a developer by profession,45-54 years old,"Employed, full-time",Remote,Apples,Hobby;Contribute to open-source projects;Other...,"Master’s degree (M.A., M.S., M.Eng., MBA, etc.)",Books / Physical media;Colleague;On the job tr...,Technical documentation;Blogs;Books;Written Tu...,API document(s) and/or SDK document(s);User gu...,37,27,Developer Experience,NaN,NaN,NaN,NaN,NaN,United Kingdom of Great Britain and Northern I...,NaN,NaN,C#,C#,C#,Firebase Realtime Database,Firebase Realtime Database,Firebase Realtime Database,Google Cloud,Google Cloud,Google Cloud,ASP.NET CORE,ASP.NET CORE,ASP.NET CORE,Rasberry Pi,Rasberry Pi,Rasberry Pi,.NET (5+) ;.NET Framework (1.0 - 4.8);.NET MAUI,.NET (5+) ;.NET Framework (1.0 - 4.8);.NET MAUI,.NET (5+) ;.NET Framework (1.0 - 4.8);.NET MAUI,MSBuild,MSBuild,MSBuild,Visual Studio,Visual Studio,Visual Studio,Windows,Windows,NaN,NaN,NaN,Google Chat;Google Meet;Microsoft Teams;Zoom,Google Chat;Google Meet;Zoom,Google Chat;Google Meet;Zoom,NaN,NaN,NaN,Stack Overflow;Stack Exchange;Stack Overflow B...,Multiple times per day,Yes,Multiple times per day,Quickly finding code solutions;Finding reliabl...,"Yes, definitely","No, and I don't plan to",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,No,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Appropriate in length,Easy,NaN,NaN
4,I am learning to code,18-24 years old,"Student, full-time",NaN,Apples,NaN,Some college/university study without earning ...,"Other online resources (e.g., videos, blogs, f...",Stack Overflow;How-to videos;Interactive tutorial,NaN,4,NaN,"Developer, full-stack",NaN,NaN,NaN,NaN,NaN,Canada,NaN,NaN,C;C++;HTML/CSS;Java;JavaScript;PHP;PowerShell;...,HTML/CSS;Java;JavaScript;PowerShell;Python;SQL...,HTML/CSS;Java;JavaScript;PowerShell;Python;SQL...,MongoDB;MySQL;PostgreSQL;SQLite,MongoDB;MySQL;PostgreSQL,MongoDB;MySQL;PostgreSQL,Amazon Web Services (AWS);Fly.io;Heroku,Amazon Web Services (AWS);Vercel,Amazon Web Services (AWS),jQuery;Next.js;Node.js;React;WordPress,jQuery;Next.js;Node.js;React,jQuery;Next.js;Node.js;React,Rasberry Pi,NaN,NaN,NumPy;Pandas;Ruff;TensorFlow,NaN,NaN,Docker;npm;Pip,Docker;Kubernetes;npm,Docker;npm,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Stack Overflow,Daily or almost daily,No,NaN,Quickly finding code solutions,"No, not really",Yes,Very favorable,Increase productivity;Greater efficiency;Impro...,Somewhat trust,Bad at handling complex tasks,Learning about a codebase;Project planning;Wri...,Testing code;Committing and reviewing code;Pre...,NaN,Learning about a codebase;Project planning;Wri...,NaN,NaN,NaN,NaN,No,Circulating misinformation or disinformation;M...,Don’t trust the output or answers,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Too long,Easy,NaN,NaN
5,I am a developer by profession,18-24 years old,"Student, full-time",NaN,Apples,NaN,"Secondary school (e.g. American high school, G...","Other online resources (e.g., videos, blogs, f...",Technical documentation;Blogs;Written Tutorial...,API document(s) and/or SDK document(s);User gu...,9,NaN,"Developer, full-stack",NaN,NaN,NaN,NaN,NaN,Norway,NaN,NaN,C++;HTML/CSS;JavaScript;Lua;Python;Rust,C++;HTML/CSS;JavaScript;Lua;Python,C++;HTML/CSS;JavaScript;Lua;Python,PostgreSQL;SQLite,PostgreSQL;SQLite,PostgreSQL;SQLite,NaN,NaN,NaN,NaN,NaN,NaN,CMake;Cargo;Rasberry Pi,CMake;Rasberry Pi,CMake;Rasberry Pi,NaN,NaN,NaN,APT;Make;npm,APT;Make,APT;Make,Vim,Vim,Vim,Other (please specify):,NaN,GitHub Discussions;Markdown File;Obsidian;Stac...,GitHub Discussions;Markdown File;Obsidian,GitHub Discussions;Markdown File;Obsidian,Discord;Whatsapp,Discord;Whatsapp,Discord;Whatsapp,NaN,NaN,NaN,Stack Overflow for Teams (private knowledge sh...,Multiple times per day,Yes,Multiple times per day,Quickly finding code solutions;Engage with com...,"Yes, definitely","No, and I don't plan to",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Too short,Easy,NaN,NaN

In [41]:
df.sort_values(by = ["Country","CompTotal"],ascending = [True,False],inplace = True)

In [42]:
df[["Country","CompTotal"]].head(100)

                Country     CompTotal
ResponseId
17375       Afghanistan  1.000000e+53
8815        Afghanistan  1.000000e+44
60332       Afghanistan  9.347772e+09
1566        Afghanistan  2.500000e+08
37549       Afghanistan  8.000000e+05
49949       Afghanistan  7.000000e+05
61493       Afghanistan  7.000000e+05
14673       Afghanistan  6.000000e+05
6942        Afghanistan  4.800000e+05
14613       Afghanistan  2.500000e+05
9825        Afghanistan  5.000000e+04
55237       Afghanistan  3.200000e+04
39346       Afghanistan  2.000000e+04
48576       Afghanistan  9.999000e+03
1241        Afghanistan  1.236000e+03
12281       Afghanistan  1.000000e+03
38003       Afghanistan  6.660000e+02
22246       Afghanistan  4.500000e+01
42168       Afghanistan  2.100000e+01
44402       Afghanistan  9.000000e+00
25201       Afghanistan  2.000000e+00
18723       Afghanistan  1.000000e+00
41147       Afghanistan  0.000000e+00
15329       Afghanistan  0.000000e+00
1378        Afghanistan           NaN
33453       Afghanistan           NaN
55671       Afghanistan           NaN
1328        Afghanistan           NaN
31476       Afghanistan           NaN
64494       Afghanistan           NaN
64869       Afghanistan           NaN
46020       Afghanistan           NaN
50987       Afghanistan           NaN
59308       Afghanistan           NaN
29914       Afghanistan           NaN
32421       Afghanistan           NaN
59278       Afghanistan           NaN
17567       Afghanistan           NaN
60268       Afghanistan           NaN
37968       Afghanistan           NaN
25712       Afghanistan           NaN
31269       Afghanistan           NaN
18321       Afghanistan           NaN
33102       Afghanistan           NaN
51544       Afghanistan           NaN
55953       Afghanistan           NaN
36195       Afghanistan           NaN
3823        Afghanistan           NaN
59483       Afghanistan           NaN
50360       Afghanistan           NaN
2138        Afghanistan           NaN
29769       Afghanistan           NaN
28559       Afghanistan           NaN
36518       Afghanistan           NaN
7690        Afghanistan           NaN
64343       Afghanistan           NaN
27873           Albania  6.000000e+06
11267           Albania  6.000000e+06
11575           Albania  6.000000e+06
25187           Albania  3.300000e+06
33016           Albania  2.000000e+06
25681           Albania  1.200000e+05
14311           Albania  1.000000e+05
44201           Albania  1.000000e+05
8239            Albania  8.000000e+04
48710           Albania  6.600000e+04
28182           Albania  4.500000e+04
63234           Albania  3.300000e+04
27693           Albania  2.220000e+04
51057           Albania  2.000000e+04
56684           Albania  9.500000e+03
18474           Albania  2.500000e+03
644             Albania           NaN
22385           Albania           NaN
39463           Albania           NaN
8073            Albania           NaN
25970           Albania           NaN
5055            Albania           NaN
16312           Albania           NaN
31910           Albania           NaN
18902           Albania           NaN
61092           Albania           NaN
63403           Albania           NaN
53751           Albania           NaN
10080           Albania           NaN
49574           Albania           NaN
23385           Albania           NaN
48703           Albania           NaN
50411           Albania           NaN
12211           Albania           NaN
49937           Albania           NaN
41806           Albania           NaN
55633           Albania           NaN
12587           Albania           NaN
20497           Albania           NaN
57049           Albania           NaN
56884           Albania           NaN
54468           Albania           NaN
61584           Albania           NaN
12878           Albania           NaN

In [43]:
df["CompTotal"].nlargest(10)

ResponseId
14355    1.000000e+150
34279     1.000000e+65
17375     1.000000e+53
8815      1.000000e+44
20038     8.000000e+27
24678     1.000000e+20
27269     1.111111e+15
52486     3.040302e+14
46993     7.587459e+13
59888     7.777778e+12
Name: CompTotal, dtype: float64

In [45]:
df.nsmallest(10,"CompTotal")

,MainBranch,Age,Employment,RemoteWork,Check,CodingActivities,EdLevel,LearnCode,LearnCodeOnline,TechDoc,YearsCode,YearsCodePro,DevType,OrgSize,PurchaseInfluence,BuyNewTool,BuildvsBuy,TechEndorse,Country,Currency,CompTotal,LanguageHaveWorkedWith,LanguageWantToWorkWith,LanguageAdmired,DatabaseHaveWorkedWith,DatabaseWantToWorkWith,DatabaseAdmired,PlatformHaveWorkedWith,PlatformWantToWorkWith,PlatformAdmired,WebframeHaveWorkedWith,WebframeWantToWorkWith,WebframeAdmired,EmbeddedHaveWorkedWith,EmbeddedWantToWorkWith,EmbeddedAdmired,MiscTechHaveWorkedWith,MiscTechWantToWorkWith,MiscTechAdmired,ToolsTechHaveWorkedWith,ToolsTechWantToWorkWith,ToolsTechAdmired,NEWCollabToolsHaveWorkedWith,NEWCollabToolsWantToWorkWith,NEWCollabToolsAdmired,OpSysPersonal use,OpSysProfessional use,OfficeStackAsyncHaveWorkedWith,OfficeStackAsyncWantToWorkWith,OfficeStackAsyncAdmired,OfficeStackSyncHaveWorkedWith,OfficeStackSyncWantToWorkWith,OfficeStackSyncAdmired,AISearchDevHaveWorkedWith,AISearchDevWantToWorkWith,AISearchDevAdmired,NEWSOSites,SOVisitFreq,SOAccount,SOPartFreq,SOHow,SOComm,AISelect,AISent,AIBen,AIAcc,AIComplex,AIToolCurrently Using,AIToolInterested in Using,AIToolNot interested in Using,AINextMuch more integrated,AINextNo change,AINextMore integrated,AINextLess integrated,AINextMuch less integrated,AIThreat,AIEthics,AIChallenges,TBranch,ICorPM,WorkExp,Knowledge_1,Knowledge_2,Knowledge_3,Knowledge_4,Knowledge_5,Knowledge_6,Knowledge_7,Knowledge_8,Knowledge_9,Frequency_1,Frequency_2,Frequency_3,TimeSearching,TimeAnswering,Frustration,ProfessionalTech,ProfessionalCloud,ProfessionalQuestion,Industry,JobSatPoints_1,JobSatPoints_4,JobSatPoints_5,JobSatPoints_6,JobSatPoints_7,JobSatPoints_8,JobSatPoints_9,JobSatPoints_10,JobSatPoints_11,SurveyLength,SurveyEase,ConvertedCompYearly,JobSat
ResponseId,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,
41147,I am a developer by profession,35-44 years old,"Independent contractor, freelancer, or self-em...",Remote,Apples,Hobby;Other (please specify):,Some college/university study without earning ...,"Other online resources (e.g., videos, blogs, f...",Technical documentation;Blogs;Interactive tuto...,API document(s) and/or SDK document(s);User gu...,25,21,"Developer, full-stack","Just me - I am a freelancer, sole proprietor, ...",I have a great deal of influence,Ask developers I know/work with,Is ready-to-go but also customizable for growt...,APIs;Integrated developer community;Reputation...,Afghanistan,AFN\tAfghan afghani,0.0,JavaScript,Go;JavaScript;Rust,JavaScript,MongoDB;PostgreSQL;SQLite;Supabase,PostgreSQL;SQLite;Supabase,PostgreSQL;SQLite;Supabase,NaN,NaN,NaN,Svelte,Svelte,Svelte,NaN,NaN,NaN,Tauri,Tauri,Tauri,Docker;npm;pnpm;Vite,pnpm;Vite,pnpm;Vite,IntelliJ IDEA,IntelliJ IDEA,IntelliJ IDEA,Arch,Arch,NaN,NaN,NaN,Discord;Jitsi,Discord;Jitsi,Discord;Jitsi,NaN,NaN,NaN,Stack Overflow,A few times per month or weekly,No,NaN,Other (please specify):,"No, not at all","No, and I don't plan to",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Appropriate in length,Neither easy nor difficult,NaN,NaN
15329,I am a developer by profession,25-34 years old,"Employed, full-time","Hybrid (some remote, some in-person)",Apples,Hobby;Professional development or self-paced l...,"Master’s degree (M.A., M.S., M.Eng., MBA, etc.)",Books / Physical media;Other online resources ...,Technical documentation;Books;Written Tutorial...,API document(s) and/or SDK document(s);User gu...,10,10,Data engineer,20 to 99 employees,I have some influence,Start a free trial;Ask developers I know/work ...,Out-of-the-box is ready to go with little need...,Integrated developer community;Reputation for ...,Afghanistan,AED United Arab Emirates dirham,0.0,Python;SQL,Go;HTML/CSS;Python;Rust;SQL,Python;SQL,DuckDB;PostgreSQL,Clickhouse;DuckDB;PostgreSQL;Snowflake,DuckDB;PostgreSQL,Amazon Web Services (AWS);Digital Ocean,Amazon Web Services (AWS);Digital Ocean;Google...,Amazon Web Services (AWS);Digital Ocean,FastAPI,Django;FastAPI;Htmx;Node.js;React,FastAPI,NaN,NaN,NaN,Apache Spark;Pandas;Scikit-Learn,Apache Kafka;mlflow;Pandas;RabbitMQ,Pandas,Docker;Homebrew;Kubernetes;Make;Pip;Terraform,Docker;Homebrew;Kubernetes;Make;Pip;Terraform,Docker;Homebrew;Kubernetes;Make;Pip;Terraform,DataGrip;IPython;Jupyter Notebook/JupyterLab;N...,DataGrip;IPython;Jupyter Notebook/JupyterLab;N...,DataGrip;IPython;Jupyter Notebook/JupyterLab;N...,MacOS,Debian;MacOS;Ubuntu,Jira;Markdown File;Miro;Notion,Markdown File;Miro;Notion;Obsidian,Markdown File;Miro;Notion,Google Meet;Signal;Whatsapp,Google Meet,Google Meet,ChatGPT;GitHub Copilot,ChatGPT,ChatGPT,Stack Overflow;Stack Exchange,A few times per week,Yes,Less than once per month or monthly,Quickly finding code solutions;Finding reliabl...,"No, not at all",Yes,Favorable,Increase productivity;Speed up learning,Somewhat distrust,Bad at handling complex tasks,Learning about a codebase;Debugging and gettin...,NaN,NaN,NaN,NaN,Learning about a codebase;Debugging and gettin...,NaN,NaN,No,Circulating misinformation or disinformation;M...,Don’t trust the output or answers;Lack of prop...,No,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Appropriate in length,Neither easy nor difficult,NaN,NaN
40089,I am a developer by profession,45-54 years old,"Employed, full-time","Hybrid (some remote, some in-person)",Apples,Hobby;Bootstrapping a business;Professional de...,"Bachelor’s degree (B.A., B.S., B.Eng., etc.)",Books / Physical media;On the job training;Oth...,Technical documentation;Blogs;Books;Written Tu...,API document(s) and/or SDK document(s);User gu...,20,16,"Developer, full-stack","1,000 to 4,999 employees",I have little or no influence,Start a free trial;Ask developers I know/work ...,Is set up to be customized and needs to be eng...,APIs;Customization;Reputation for quality and ...,Australia,AUD\tAustralian dollar,0.0,Bash/Shell (all shells);C#;Groovy;HTML/CSS;Jav...,Go;Kotlin;Objective-C;Rust,NaN,Dynamodb;Elasticsearch;H2;MariaDB;Microsoft Ac...,BigQuery;Cassandra;Couch DB;Neo4J;Redis;Snowfl...,NaN,Amazon Web Services (AWS),Google Cloud;Microsoft Azure,NaN,Express;FastAPI;Flask;Gatsby;jQuery;Next.js;No...,NaN,NaN,NaN,NaN,NaN,Hadoop;Hugging Face Transformers;JAX;NumPy;Pan...,Apache Kafka;Apache Spark;CUDA;Flutter,NaN,Ant;Docker;Gradle;Maven (build tool);npm;Pip;p...,Ansible;Terraform,NaN,Eclipse;IntelliJ IDEA;Jupyter Notebook/Jupyter...,DataGrip;WebStorm;Xcode,NaN,Debian;MacOS;Other Linux-based;Ubuntu;Windows;...,Android;iOS,Confluence;Jira;Markdown File;Miro;Wikis,Azure Devops;Monday.com,NaN,Google Meet;Microsoft Teams;Zoom,NaN,NaN,Bing AI;ChatGPT;Claude;GitHub Copilot;Google G...,Amazon Q;Meta AI;Whispr AI,NaN,Stack Overflow;Stack Exchange;Stack Overflow B...,A few times per week,Yes,Less than once per month or monthly,Quickly finding code solutions;Finding reliabl...,"Yes, somewhat",Yes,Favorable,Increase productivity;Speed up learning;Improv...,Somewhat trust,"Good, but not great at handling complex tasks",Writing code;Debugging and getting help;Search...,Documenting code;Committing and reviewing code...,NaN,NaN,NaN,Writing code;Debugging and getting help;Search...,NaN,NaN,No,Circulating misinformation or disinformation;M...,"AI tools lack context of codebase, internal a...",No,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Too long,Neither easy nor difficult,NaN,NaN
9948,"I am not primarily a developer, but I write co...",18-24 years old,"Student, full-time;Independent contractor, fre...",Remote,Apples,Hobby;Bootstrapping a business;School or acade...,"Secondary school (e.g. American high school, G...","Other online resources (e.g., videos, blogs, f...",Technical documentation;Blogs;Stack Overflow;S...,Traditional public search engine;AI-powered se...,8,8,"Developer, full-stack","Just me - I am a freelancer, sole proprietor, ...",I have a great deal of influence,Start a free trial;Visit developer communities...,Is ready-to-go but also customizable for growt...,Customization;Quality support system;Reputatio...,Australia,AUD\tAustralian dollar,0.0,Assembly;Bash/Shell (all shells);C;C#;C++;HTML...,C#;C++;HTML/CSS;JavaScript;Python;Rust;Swift,C#;C++;HTML/CSS;JavaScript;Swift,MongoDB,MongoDB,MongoDB,Amazon Web Services (AWS);Cloudflare;Heroku,Amazon Web Services (AWS);Cloudflare;Heroku,Amazon Web Services (AWS);Cloudflare;Heroku,Express;jQuery;Node.js;Vue.js,Express;Node.js,Express;Node.js,NaN,NaN,NaN,.NET (5+) ;Capacitor;Cordova;Electron;SwiftUI,.NET (5+) ;Capacitor;Cordova;Electron;React Na...,.NET (5+) ;Capacitor;Cordova;Electron;SwiftUI,Docker;Homebrew;Kubernetes;Make;npm;Unity 3D,npm;Unity 3D;Unreal Engine,npm;Unity 3D,Visual Studio;Visual Studio Code;Xcode,Visual Studio;Visual Studio Code;Xcode,Visual Studio;Visual Studio Code;Xcode,iOS;MacOS;Windows,iOS;MacOS;Windows,Notion;Trello,Obsidian;Trello,Trello,Discord,Discord,Discord,ChatGPT;GitHub Copilot;OpenAI Codex,ChatGPT;OpenAI Codex,ChatGPT;OpenAI Codex,Stack Overflow,A few times per week,Yes,Less than once per month or monthly,Quickly finding code solutions;Finding reliabl...,"Yes, somewhat",Yes,Very favorable,Increase productivity;Greater efficiency;Impro...,Somewhat trust,Very well at handling complex tasks,Learning about a codebase;Project planning;Wri...,Deployment and monitoring,NaN,Learning about a codebase;Project planning;Wri...,NaN,NaN,NaN,NaN,No,Circulating misinformation or disinformation;M...,Don’t trust the output or answers,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Appropriate in length,Easy,NaN,NaN
15163,I am a developer by profession,45-54 years old,"Independent contractor, freelancer, or self-em...",Remote,Apples,Freelance/contract work,"Bachelor’s degree (B.A., B.S., B.Eng., etc.)",Books / Physical media,NaN,NaN,38,28,"Developer, full-stack",2 to 9 employees,I have a great deal of influence,Start a free trial;Visit developer communities...,Is ready-to-go but also customizable for growt...,Connected to an open source project,Australia,AUD\tAustralian dollar,0.0,Dart;Go;Groovy;JavaScript;Python;SQL,Dart;Go;Python;SQL;TypeScript,Dart;Go;Python;SQL,PostgreSQL,PostgreSQL,PostgreSQL,"Linode, now Akamai","Linode, now Akamai","Linode, now Akamai",Django;Vue.js,Django;Htmx,Django,NaN,NaN,NaN,Flutter,Flutter,Flutter,Docker;Pip;Vite;Yarn,Docker;Vite,Docker;Vite,DataGrip;Goland;PyCharm;Visual Studio Code,DataGrip;Goland;PyCharm,DataGrip;Goland;PyCharm,Ubuntu,Ubuntu,NaN,NaN,NaN,Slack,NaN,NaN,ChatGPT,ChatGPT,ChatGPT,Stack Overflow,A few times per week,Yes,I have never participated in Q&A on Stack Over...,Quickly finding code solutions;Learning new-to...,"Yes, somewhat",Yes,Favorable,Increase productivity;Speed up learning,Somewhat trust,Bad at handling complex tasks,Writing code;Documenting code,Testing code;Search for answers;Generating con...,Learning about a codebase;Project planning;Deb...,NaN,NaN,Writing code;Documenting code,NaN,NaN,No,Circulating misinformation or disinformation;M...,Don’t trust the output or answers;AI tools lac...,No,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Too long,Neither easy nor difficult,NaN,NaN
50594,"I am not primarily a developer, but I write co...",55-64 years old,"Independent contractor, freelancer, or self-em...",Remote,Apples,Hobby;Contribute to open-source projects;Schoo...,Some college/university study without earning ...,Books / Physical media;On the job training;Oth...,Technical documentation;Blogs;Books;Written Tu...,API document(s) and/or SDK document(s);User gu...,40,30,Other (please specify):,"Just me - I am a freelancer, sole proprietor, ...",I have a great deal of influence,Start a free trial;Visit developer communities...,Is ready-to-go but also customizable for growt...,APIs;Customization;Integrated developer commun...,Australia,AUD\tAustralian dollar,0.0,Java;Python,Java;Python,Java;Python,MongoDB;MySQL,MongoDB;MySQL,MongoDB;MySQL,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Visual Studio Solution,Visual Studio Solution,Visual Studio Solution,Android Studio;Eclipse;Geany;Kate;Notepad++;Py...,Android Studio;Eclipse;Geany;Kate;Notepad++;Py...,Android Studio;Eclipse;Geany;Kate;Notepad++;Py...,Fedora;Windows,Fedora;Windows,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Stack Overflow;Stack Overflow Blog or Podcast,Multiple times per day,Yes,Multiple times per day,Quickly finding code solutions;Finding reliabl...,"No, not at all","No, and I don't plan to",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Appropriate in length,Neither easy nor difficult,NaN,NaN
51644,I am a developer by profession,18-24 years old,"Not employed, but looking for work;Independent...",In-person,Apples,Hobby;Professional development or self-paced l...,"Bachelor’s degree (B.A., B.S., B.Eng., etc.)","Other online resources (e.g., videos, blogs, f...",Technical documentation;Blogs;Written Tutorial...,User guides or README files found in the sourc...,4,Less than 1 year,"Developer, back-end","Just me - I am a freelancer, sole proprietor, ...",I have little or no influence,Start a free trial;Visit developer communities...,Is set up to be customized and needs to be eng...,Integrated developer community;Frequent update...,Azerbaijan,AZN\tAzerbaijan manat,0.0,Go;Python,Go;Rust,Go,Cassandra;MongoDB;PostgreSQL,NaN,NaN,Cloudflare;Digital Ocean,Cloudflare;Digital Ocean,Cloudflare;Digital Ocean,Django;FastAPI,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Docker,Docker;Kubernetes,Docker,Visual Studio Code,Visual Studio Code,Visual Studio Code,Ubuntu,Ubuntu,Jira,NaN,NaN,Telegram;Whatsapp,Telegram;Whatsapp,Telegram;Whatsapp,ChatGPT;GitHub Copilot,ChatGPT;GitHub Copilot,ChatGPT;GitHub Copilot,Stack Overflow;Stack Exchange,A few times per week,Yes,I have never participated in Q&A on Stack Over...,Quickly finding code solutions;Finding reliabl...,Neutral,Yes,Indifferent,Increase productivity;Greater efficiency;Speed...,Somewhat distrust,Bad at handling complex tasks,Learning about a codebase;Writing code;Documen...,Debugging and getting help;Deployment and moni...,Project planning;Testing code,NaN,NaN,Learning about a codebase;Writing code;Documen...,NaN,NaN,I'm not sure,Circulating misinformation or disinformation;M...,Don’t trust the output or answers,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Appropriate in length,Easy,NaN,NaN
24879,I am a developer by profession,18-24 years old,"Independent contractor, freelancer, or self-em...",Remote,Apples,Hobby,"Bachelor’s degree (B.A., B.S., B.Eng., etc.)","Other online resources (e.g., videos, blogs, f...",Technical documentation;Stack Overflow;Coding ...,API document(s) and/or SDK document(s);User gu...,2,1,"Developer, full-stack","Just me - I am a freelancer, sole proprietor, ...",I have some influence,Start a free trial;Read ratings or reviews on ...,Out-of-the-box is ready to go with little need...,APIs;Customization;Quality support system;AI t...,Bangladesh,BDT\tBangladeshi taka,0.0,Dart;JavaScript;PHP;Python,Dart;JavaScript;PHP;Python;TypeScript,Dart;JavaScript;PHP;Python,MySQL;SQLite,Firebase Realtime Database;MySQL;PostgreSQL;SQ...,MySQL;SQLite,Netlify;Vercel,Amazon Web Services (AWS);Google Cloud,NaN,jQuery;Laravel;Vue.js,Django;Remix;Svelte;Vue.js,Vue.js,NaN,NaN,NaN,NaN,NaN,NaN,Composer;npm;Vite,Bun;Composer;Docker;npm;Pip;Vite;Webpack;Yarn,Composer;npm;Vite,Visual Studio Code,IntelliJ IDEA;Visual Studio Code;VSCodium;WebS...,Visual Studio Code,Android;Windows,iOS;MacOS;Ubuntu,GitHub Discussions,GitHub Discussions;Jira,GitHub Discussions,Skype;Whatsapp,Skype;Telegram;Whatsapp;Zoom,Skype;Whatsapp,Bing AI;ChatGPT;GitHub Copilot;Google Gemini;T...,ChatGPT;GitHub Copilot;Google Gemini;Meta AI,ChatGPT;GitHub Copilot;Google Gemini,Stack Overflow,A few times per week,Yes,I have never participated in Q&A on Stack Over...,Quickly finding code solutions;Engage with com...,"Yes, definitely",Yes,Very favorable,Increase productivity;Greater efficiency;Speed...,Somewhat trust,"Good, but not great at handling complex tasks",Writing code;Documenting code;Debugging and ge...,Learning about a codebase;Project planning;Com...,Deployment and monitoring,Writing code;Documenting code;Debugging and ge...,NaN,NaN,NaN,NaN,Yes,Circulating misinformation or disinformation;M...,"AI tools lack context of codebase, internal a...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Too long,Neither easy nor difficult,NaN,NaN
6747,I am a developer by profession,45-54 years old,"Independent contractor, freelancer, or self-em...",Remote,Apples,I don’t code outside of work,"Bachelor’s degree (B.A., B.S., B.Eng., etc.)",Online Courses or Certification,NaN,NaN,10,7,"Developer, full-stack","Just me - I am a freelancer, sole proprietor, ...",I have a great deal of influence,Start a free trial,Is set up to be customized and needs to be eng...,Reputation for quality and excellence,Brazil,BRL\tBrazilian real,0.0,HTML/CSS;JavaScript;PowerShell;TypeScript,JavaScript;TypeScript,JavaScript;TypeScript,Dynamodb,Dynamodb,Dynamodb,Amazon Web Services (AWS),Amazon Web Services (AWS),Amazon Web Services (AWS),Node.js;React,Next.js;Node.js;React,Node.js;React,NaN,NaN,NaN,NaN,NaN,NaN,npm;Webpack,npm;Webpack,npm;Webpack,Visual Studio Code,Visual Studio Code,Visual Studio Code,Android;Windows,Windows,NaN,NaN,NaN,Discord;Google Meet;Microsoft Teams;Slack;What...,Google Meet;Whatsapp,Google Meet;Whatsapp,Amazon Q;ChatGPT;GitHub Copilot;Visual Studio ...,Amazon Q;ChatGPT;GitHub Copilot;Google Gemini;...,Amazon Q;ChatGPT;GitHub Copilot;Visual Studio ...,Stack Overflow,A few times per week,Yes,Less than once per month or monthly,Quickly finding code solutions;Finding reliabl...,"Yes, somewhat",Yes,Favorable,Increase productivity;Greater efficiency;Speed...,Somewhat distrust,Very poor at handling complex tasks,Writing code,Learning about a codebase;Project planning;Doc...,NaN,NaN,NaN,Writing code,NaN,NaN,No,Replacing jobs without options for new employm...,Don’t trust the output or answers,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Too long,Neither easy nor difficult,NaN,NaN