In [3]:
people = {
    "first" : ["Corey","Jane","John"],
    "last"  : ["Schafer","Doe","Doe"],
    "email" : ["Corey@gmail.com","Jane@gmail.com","John@yahoo.com"]
}

In [4]:
import pandas as pd

In [5]:
df = pd.DataFrame(people)

In [6]:
df

   first     last            email
0  Corey  Schafer  Corey@gmail.com
1   Jane      Doe   Jane@gmail.com
2   John      Doe   John@yahoo.com

In [7]:
df.columns

Index(['first', 'last', 'email'], dtype='object')

In [8]:
# change the columns
df.columns = ["first_name","fast_name","email"]

In [9]:
df

  first_name fast_name            email
0      Corey   Schafer  Corey@gmail.com
1       Jane       Doe   Jane@gmail.com
2       John       Doe   John@yahoo.com

In [10]:
df.columns = [x.upper() for x in df.columns]

In [11]:
df

  FIRST_NAME FAST_NAME            EMAIL
0      Corey   Schafer  Corey@gmail.com
1       Jane       Doe   Jane@gmail.com
2       John       Doe   John@yahoo.com

In [12]:
df.columns = df.columns.str.replace("_"," ")

In [13]:
df

  FIRST NAME FAST NAME            EMAIL
0      Corey   Schafer  Corey@gmail.com
1       Jane       Doe   Jane@gmail.com
2       John       Doe   John@yahoo.com

In [14]:
df.columns = df.columns.str.replace(" ","_")

In [15]:
df

  FIRST_NAME FAST_NAME            EMAIL
0      Corey   Schafer  Corey@gmail.com
1       Jane       Doe   Jane@gmail.com
2       John       Doe   John@yahoo.com

In [16]:
df.rename(columns = {"FIRST_NAME":"first"
                    ,"FAST_NAME":"last",
                    "EMAIL" : "email"},inplace = True)

In [17]:
df

   first     last            email
0  Corey  Schafer  Corey@gmail.com
1   Jane      Doe   Jane@gmail.com
2   John      Doe   John@yahoo.com

In [18]:
df.loc[2] = ["John","Smith","Smit@gmail.com"]

In [19]:
df.loc[2,["last","email"]] = ["Doe","Doe@gmail.com"]

In [20]:
df

   first     last            email
0  Corey  Schafer  Corey@gmail.com
1   Jane      Doe   Jane@gmail.com
2   John      Doe    Doe@gmail.com

In [21]:
df.loc[2,"last"] = "Smith"

In [22]:
df

   first     last            email
0  Corey  Schafer  Corey@gmail.com
1   Jane      Doe   Jane@gmail.com
2   John    Smith    Doe@gmail.com

In [23]:
df.at[2,"last"] = "Doe"

In [24]:
df

   first     last            email
0  Corey  Schafer  Corey@gmail.com
1   Jane      Doe   Jane@gmail.com
2   John      Doe    Doe@gmail.com

In [25]:
# filt = (df["email"] == "Doe@gmail.com")
# df[filt]["last"] = "Smith" # dont use this it will give you warning

In [26]:
df

   first     last            email
0  Corey  Schafer  Corey@gmail.com
1   Jane      Doe   Jane@gmail.com
2   John      Doe    Doe@gmail.com

In [27]:
filt = (df["email"] == "Doe@gmail.com")
df.loc[filt,"last"] = "Smith"

In [28]:
df["email"] = df["email"].str.lower() # changle multple rows at same time

In [29]:
df

   first     last            email
0  Corey  Schafer  corey@gmail.com
1   Jane      Doe   jane@gmail.com
2   John    Smith    doe@gmail.com

In [30]:
### how to use apply method 
# just simply add any function as argument

In [31]:
df["email"].apply(len) # apply for series

0    15
1    14
2    13
Name: email, dtype: int64

In [32]:
def update_email(email):
    return email.upper()

In [33]:
df["email"] = df["email"].apply(update_email)

In [34]:
df

   first     last            email
0  Corey  Schafer  COREY@GMAIL.COM
1   Jane      Doe   JANE@GMAIL.COM
2   John    Smith    DOE@GMAIL.COM

In [35]:
df["email"] = df["email"].apply(lambda string:string.lower())

In [36]:
df

   first     last            email
0  Corey  Schafer  corey@gmail.com
1   Jane      Doe   jane@gmail.com
2   John    Smith    doe@gmail.com

In [37]:
# apply for data-frame

In [38]:
df.apply(len,axis = "columns")

0    3
1    3
2    3
dtype: int64

In [39]:
df.apply(pd.Series.min)

first              Corey
last                 Doe
email    corey@gmail.com
dtype: object

In [40]:
df.apply(lambda x:x.min())

first              Corey
last                 Doe
email    corey@gmail.com
dtype: object

In [45]:
df.applymap(len)

/tmp/ipykernel_6088/1485728669.py:1: FutureWarning: DataFrame.applymap has been deprecated. Use DataFrame.map instead.
  df.applymap(len)

   first  last  email
0      5     7     15
1      4     3     14
2      4     5     13

In [49]:
# applymap function which is use to make changes in the whole dataFrame
# this may give you a warning because this method is a bit old you can
# search for another updated method

In [48]:
df.applymap(str.lower)

/tmp/ipykernel_6088/357608748.py:1: FutureWarning: DataFrame.applymap has been deprecated. Use DataFrame.map instead.
  df.applymap(str.lower)

   first     last            email
0  corey  schafer  corey@gmail.com
1   jane      doe   jane@gmail.com
2   john    smith    doe@gmail.com

In [50]:
df["first"].map({"Corey" : "Chris","Jane":"Mary"})

0    Chris
1     Mary
2      NaN
Name: first, dtype: object

In [51]:
df

   first     last            email
0  Corey  Schafer  corey@gmail.com
1   Jane      Doe   jane@gmail.com
2   John    Smith    doe@gmail.com

In [53]:
df["first"] = df["first"].replace({"Corey" : "Chris","Jane":"Mary"})

In [54]:
df

   first     last            email
0  Chris  Schafer  corey@gmail.com
1   Mary      Doe   jane@gmail.com
2   John    Smith    doe@gmail.com

In [55]:
# stack overflow survey data

In [57]:
df = pd.read_csv("data/survey_results_public.csv")
schema_df = pd.read_csv("data/survey_results_schema.csv")

In [58]:
pd.set_option("display.max_columns",df.shape[1])
pd.set_option("display.max_rows",df.shape[0])

In [59]:
df.head()

,ResponseId,MainBranch,Age,Employment,RemoteWork,Check,CodingActivities,EdLevel,LearnCode,LearnCodeOnline,TechDoc,YearsCode,YearsCodePro,DevType,OrgSize,PurchaseInfluence,BuyNewTool,BuildvsBuy,TechEndorse,Country,Currency,CompTotal,LanguageHaveWorkedWith,LanguageWantToWorkWith,LanguageAdmired,DatabaseHaveWorkedWith,DatabaseWantToWorkWith,DatabaseAdmired,PlatformHaveWorkedWith,PlatformWantToWorkWith,PlatformAdmired,WebframeHaveWorkedWith,WebframeWantToWorkWith,WebframeAdmired,EmbeddedHaveWorkedWith,EmbeddedWantToWorkWith,EmbeddedAdmired,MiscTechHaveWorkedWith,MiscTechWantToWorkWith,MiscTechAdmired,ToolsTechHaveWorkedWith,ToolsTechWantToWorkWith,ToolsTechAdmired,NEWCollabToolsHaveWorkedWith,NEWCollabToolsWantToWorkWith,NEWCollabToolsAdmired,OpSysPersonal use,OpSysProfessional use,OfficeStackAsyncHaveWorkedWith,OfficeStackAsyncWantToWorkWith,OfficeStackAsyncAdmired,OfficeStackSyncHaveWorkedWith,OfficeStackSyncWantToWorkWith,OfficeStackSyncAdmired,AISearchDevHaveWorkedWith,AISearchDevWantToWorkWith,AISearchDevAdmired,NEWSOSites,SOVisitFreq,SOAccount,SOPartFreq,SOHow,SOComm,AISelect,AISent,AIBen,AIAcc,AIComplex,AIToolCurrently Using,AIToolInterested in Using,AIToolNot interested in Using,AINextMuch more integrated,AINextNo change,AINextMore integrated,AINextLess integrated,AINextMuch less integrated,AIThreat,AIEthics,AIChallenges,TBranch,ICorPM,WorkExp,Knowledge_1,Knowledge_2,Knowledge_3,Knowledge_4,Knowledge_5,Knowledge_6,Knowledge_7,Knowledge_8,Knowledge_9,Frequency_1,Frequency_2,Frequency_3,TimeSearching,TimeAnswering,Frustration,ProfessionalTech,ProfessionalCloud,ProfessionalQuestion,Industry,JobSatPoints_1,JobSatPoints_4,JobSatPoints_5,JobSatPoints_6,JobSatPoints_7,JobSatPoints_8,JobSatPoints_9,JobSatPoints_10,JobSatPoints_11,SurveyLength,SurveyEase,ConvertedCompYearly,JobSat
0,1,I am a developer by profession,Under 18 years old,"Employed, full-time",Remote,Apples,Hobby,Primary/elementary school,Books / Physical media,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,United States of America,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,I have never visited Stack Overflow or the Sta...,NaN,NaN,NaN,NaN,NaN,Yes,Very favorable,Increase productivity,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,No,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,2,I am a developer by profession,35-44 years old,"Employed, full-time",Remote,Apples,Hobby;Contribute to open-source projects;Other...,"Bachelor’s degree (B.A., B.S., B.Eng., etc.)",Books / Physical media;Colleague;On the job tr...,Technical documentation;Blogs;Books;Written Tu...,API document(s) and/or SDK document(s);User gu...,20,17,"Developer, full-stack",NaN,NaN,NaN,NaN,NaN,United Kingdom of Great Britain and Northern I...,NaN,NaN,Bash/Shell (all shells);Go;HTML/CSS;Java;JavaS...,Bash/Shell (all shells);Go;HTML/CSS;Java;JavaS...,Bash/Shell (all shells);Go;HTML/CSS;Java;JavaS...,Dynamodb;MongoDB;PostgreSQL,PostgreSQL,PostgreSQL,Amazon Web Services (AWS);Heroku;Netlify,Amazon Web Services (AWS);Heroku;Netlify,Amazon Web Services (AWS);Heroku;Netlify,Express;Next.js;Node.js;React,Express;Htmx;Node.js;React;Remix,Express;Node.js;React,NaN,NaN,NaN,NaN,NaN,NaN,Docker;Homebrew;Kubernetes;npm;Vite;Webpack,Docker;Homebrew;Kubernetes;npm;Vite;Webpack,Docker;Homebrew;Kubernetes;npm;Vite;Webpack,PyCharm;Visual Studio Code;WebStorm,PyCharm;Visual Studio Code;WebStorm,PyCharm;Visual Studio Code;WebStorm,MacOS;Windows,MacOS,NaN,NaN,NaN,Microsoft Teams;Slack,Slack,Slack,NaN,NaN,NaN,Stack Overflow for Teams (private knowledge sh...,Multiple times per day,Yes,Multiple times per day,Quickly finding code solutions;Finding reliabl...,"Yes, definitely","No, and I don't plan to",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Yes,Individual contributor,17.0,Agree,Disagree,Agree,Agree,Agree,Neither agree nor disagree,Disagree,Agree,Agree,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,NaN,NaN,NaN,NaN
2,3,I am a developer by profession,45-54 years old,"Employed, full-time",Remote,Apples,Hobby;Contribute to open-source projects;Other...,"Master’s degree (M.A., M.S., M.Eng., MBA, etc.)",Books / Physical media;Colleague;On the job tr...,Technical documentation;Blogs;Books;Written Tu...,API document(s) and/or SDK document(s);User gu...,37,27,Developer Experience,NaN,NaN,NaN,NaN,NaN,United Kingdom of Great Britain and Northern I...,NaN,NaN,C#,C#,C#,Firebase Realtime Database,Firebase Realtime Database,Firebase Realtime Database,Google Cloud,Google Cloud,Google Cloud,ASP.NET CORE,ASP.NET CORE,ASP.NET CORE,Rasberry Pi,Rasberry Pi,Rasberry Pi,.NET (5+) ;.NET Framework (1.0 - 4.8);.NET MAUI,.NET (5+) ;.NET Framework (1.0 - 4.8);.NET MAUI,.NET (5+) ;.NET Framework (1.0 - 4.8);.NET MAUI,MSBuild,MSBuild,MSBuild,Visual Studio,Visual Studio,Visual Studio,Windows,Windows,NaN,NaN,NaN,Google Chat;Google Meet;Microsoft Teams;Zoom,Google Chat;Google Meet;Zoom,Google Chat;Google Meet;Zoom,NaN,NaN,NaN,Stack Overflow;Stack Exchange;Stack Overflow B...,Multiple times per day,Yes,Multiple times per day,Quickly finding code solutions;Finding reliabl...,"Yes, definitely","No, and I don't plan to",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,No,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Appropriate in length,Easy,NaN,NaN
3,4,I am learning to code,18-24 years old,"Student, full-time",NaN,Apples,NaN,Some college/university study without earning ...,"Other online resources (e.g., videos, blogs, f...",Stack Overflow;How-to videos;Interactive tutorial,NaN,4,NaN,"Developer, full-stack",NaN,NaN,NaN,NaN,NaN,Canada,NaN,NaN,C;C++;HTML/CSS;Java;JavaScript;PHP;PowerShell;...,HTML/CSS;Java;JavaScript;PowerShell;Python;SQL...,HTML/CSS;Java;JavaScript;PowerShell;Python;SQL...,MongoDB;MySQL;PostgreSQL;SQLite,MongoDB;MySQL;PostgreSQL,MongoDB;MySQL;PostgreSQL,Amazon Web Services (AWS);Fly.io;Heroku,Amazon Web Services (AWS);Vercel,Amazon Web Services (AWS),jQuery;Next.js;Node.js;React;WordPress,jQuery;Next.js;Node.js;React,jQuery;Next.js;Node.js;React,Rasberry Pi,NaN,NaN,NumPy;Pandas;Ruff;TensorFlow,NaN,NaN,Docker;npm;Pip,Docker;Kubernetes;npm,Docker;npm,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Stack Overflow,Daily or almost daily,No,NaN,Quickly finding code solutions,"No, not really",Yes,Very favorable,Increase productivity;Greater efficiency;Impro...,Somewhat trust,Bad at handling complex tasks,Learning about a codebase;Project planning;Wri...,Testing code;Committing and reviewing code;Pre...,NaN,Learning about a codebase;Project planning;Wri...,NaN,NaN,NaN,NaN,No,Circulating misinformation or disinformation;M...,Don’t trust the output or answers,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Too long,Easy,NaN,NaN
4,5,I am a developer by profession,18-24 years old,"Student, full-time",NaN,Apples,NaN,"Secondary school (e.g. American high school, G...","Other online resources (e.g., videos, blogs, f...",Technical documentation;Blogs;Written Tutorial...,API document(s) and/or SDK document(s);User gu...,9,NaN,"Developer, full-stack",NaN,NaN,NaN,NaN,NaN,Norway,NaN,NaN,C++;HTML/CSS;JavaScript;Lua;Python;Rust,C++;HTML/CSS;JavaScript;Lua;Python,C++;HTML/CSS;JavaScript;Lua;Python,PostgreSQL;SQLite,PostgreSQL;SQLite,PostgreSQL;SQLite,NaN,NaN,NaN,NaN,NaN,NaN,CMake;Cargo;Rasberry Pi,CMake;Rasberry Pi,CMake;Rasberry Pi,NaN,NaN,NaN,APT;Make;npm,APT;Make,APT;Make,Vim,Vim,Vim,Other (please specify):,NaN,GitHub Discussions;Markdown File;Obsidian;Stac...,GitHub Discussions;Markdown File;Obsidian,GitHub Discussions;Markdown File;Obsidian,Discord;Whatsapp,Discord;Whatsapp,Discord;Whatsapp,NaN,NaN,NaN,Stack Overflow for Teams (private knowledge sh...,Multiple times per day,Yes,Multiple times per day,Quickly finding code solutions;Engage with com...,"Yes, definitely","No, and I don't plan to",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Too short,Easy,NaN,NaN

In [73]:
df.rename(columns = {"CompTotal":"Salary"},inplace = True)

In [74]:
df["Salary"]

0                  NaN
1                  NaN
2                  NaN
3                  NaN
4                  NaN
5                  NaN
6                  NaN
7                  NaN
8                  NaN
9                  NaN
10                 NaN
11                 NaN
12                 NaN
13                 NaN
14                 NaN
15                 NaN
16                 NaN
17                 NaN
18                 NaN
19                 NaN
20                 NaN
21                 NaN
22                 NaN
23                 NaN
24                 NaN
25                 NaN
26                 NaN
27                 NaN
28                 NaN
29                 NaN
30                 NaN
31                 NaN
32                 NaN
33                 NaN
34                 NaN
35                 NaN
36                 NaN
37                 NaN
38                 NaN
39                 NaN
40                 NaN
41                 NaN
42                 NaN
43                 NaN
44                 NaN
45                 NaN
46                 NaN
47                 NaN
48                 NaN
49                 NaN
50                 NaN
51                 NaN
52                 NaN
53                 NaN
54                 NaN
55                 NaN
56                 NaN
57                 NaN
58                 NaN
59                 NaN
60                 NaN
61                 NaN
62                 NaN
63                 NaN
64                 NaN
65                 NaN
66                 NaN
67                 NaN
68                 NaN
69                 NaN
70                 NaN
71                 NaN
72        2.040000e+06
73                 NaN
74                 NaN
75                 NaN
76                 NaN
77                 NaN
78                 NaN
79                 NaN
80                 NaN
81                 NaN
82                 NaN
83                 NaN
84                 NaN
85                 NaN
86                 NaN
87                 NaN
88                 NaN
89                 NaN
90                 NaN
91                 NaN
92                 NaN
93                 NaN
94                 NaN
95                 NaN
96                 NaN
97                 NaN
98                 NaN
99                 NaN
100                NaN
101                NaN
102                NaN
103                NaN
104                NaN
105                NaN
106                NaN
107                NaN
108                NaN
109                NaN
110                NaN
111                NaN
112                NaN
113                NaN
114                NaN
115                NaN
116                NaN
117                NaN
118                NaN
119                NaN
120                NaN
121                NaN
122                NaN
123                NaN
124                NaN
125                NaN
126                NaN
127                NaN
128                NaN
129                NaN
130                NaN
131                NaN
132                NaN
133                NaN
134                NaN
135                NaN
136                NaN
137                NaN
138                NaN
139                NaN
140                NaN
141                NaN
142                NaN
143                NaN
144                NaN
145                NaN
146                NaN
147                NaN
148                NaN
149                NaN
150                NaN
151                NaN
152                NaN
153                NaN
154                NaN
155                NaN
156                NaN
157                NaN
158                NaN
159                NaN
160                NaN
161                NaN
162                NaN
163                NaN
164                NaN
165                NaN
166                NaN
167                NaN
168                NaN
169                NaN
170                NaN
171                NaN
172                NaN
173                NaN
174                NaN
175                NaN
176                NaN
177                NaN
178                NaN
179                NaN
180                NaN
181                NaN
182                NaN
183                NaN
184                NaN
185                NaN
186                NaN
187                NaN
188                NaN
189                NaN
190                NaN
191                NaN
192                NaN
193                NaN
194                NaN
195                NaN
196                NaN
197                NaN
198                NaN
199                NaN
200                NaN
201                NaN
202                NaN
203                NaN
204                NaN
205                NaN
206                NaN
207                NaN
208                NaN
209                NaN
210                NaN
211                NaN
212                NaN
213                NaN
214                NaN
215                NaN
216                NaN
217                NaN
218                NaN
219                NaN
220                NaN
221                NaN
222                NaN
223                NaN
224                NaN
225                NaN
226                NaN
227                NaN
228                NaN
229                NaN
230                NaN
231                NaN
232                NaN
233                NaN
234                NaN
235                NaN
236                NaN
237                NaN
238                NaN
239                NaN
240                NaN
241                NaN
242                NaN
243                NaN
244                NaN
245                NaN
246                NaN
247                NaN
248                NaN
249                NaN
250                NaN
251                NaN
252                NaN
253                NaN
254                NaN
255                NaN
256                NaN
257                NaN
258                NaN
259                NaN
260                NaN
261                NaN
262                NaN
263                NaN
264                NaN
265                NaN
266                NaN
267                NaN
268                NaN
269                NaN
270                NaN
271                NaN
272                NaN
273                NaN
274                NaN
275                NaN
276                NaN
277                NaN
278                NaN
279                NaN
280                NaN
281                NaN
282                NaN
283                NaN
284                NaN
285                NaN
286                NaN
287                NaN
288                NaN
289                NaN
290                NaN
291                NaN
292                NaN
293                NaN
294                NaN
295                NaN
296                NaN
297                NaN
298                NaN
299                NaN
300                NaN
301                NaN
302                NaN
303                NaN
304                NaN
305                NaN
306                NaN
307                NaN
308                NaN
309                NaN
310                NaN
311                NaN
312                NaN
313                NaN
314                NaN
315                NaN
316                NaN
317                NaN
318                NaN
319                NaN
320                NaN
321                NaN
322                NaN
323                NaN
324                NaN
325                NaN
326                NaN
327                NaN
328                NaN
329                NaN
330                NaN
331                NaN
332                NaN
333                NaN
334                NaN
335                NaN
336                NaN
337                NaN
338                NaN
339                NaN
340                NaN
341                NaN
342                NaN
343                NaN
344                NaN
345                NaN
346                NaN
347                NaN
348                NaN
349                NaN
350                NaN
351                NaN
352                NaN
353                NaN
354                NaN
355                NaN
356                NaN
357                NaN
358                NaN
359                NaN
360                NaN
361                NaN
362                NaN
363                NaN
364                NaN
365                NaN
366                NaN
367                NaN
368                NaN
369                NaN
370                NaN
371                NaN
372                NaN
373                NaN
374       2.800000e+04
375                NaN
376                NaN
377                NaN
378                NaN
379       8.500000e+04
380                NaN
381                NaN
382                NaN
383                NaN
384                NaN
385       5.000000e+04
386                NaN
387                NaN
388                NaN
389       1.100000e+05
390                NaN
391                NaN
392       1.264200e+05
393                NaN
394                NaN
395       9.500000e+04
396                NaN
397                NaN
398       1.950000e+05
399                NaN
400                NaN
401                NaN
402                NaN
403       3.500000e+04
404                NaN
405                NaN
406                NaN
407                NaN
408                NaN
409       5.400000e+04
410                NaN
411                NaN
412                NaN
413                NaN
414       1.450000e+05
415       7.400000e+04
416       1.700000e+05
417       2.700000e+04
418                NaN
419                NaN
420                NaN
421                NaN
422                NaN
423       6.200000e+04
424       8.000000e+04
425       9.800000e+04
426       5.000000e+04
427                NaN
428       2.300000e+05
429                NaN
430                NaN
431       8.500000e+04
432       1.600000e+05
433                NaN
434                NaN
435                NaN
436                NaN
437                NaN
438                NaN
439                NaN
440       1.100000e+05
441                NaN
442       1.900000e+05
443       1.270000e+05
444       1.150000e+05
445       1.140000e+06
446       6.500000e+04
447       1.150000e+05
448                NaN
449                NaN
450                NaN
451       1.200000e+06
452                NaN
453                NaN
454                NaN
455       9.487000e+04
456       3.000000e+05
457                NaN
458       1.200000e+06
459       5.100000e+04
460                NaN
461       3.500000e+05
462                NaN
463                NaN
464       2.600000e+04
465       1.000000e+05
466                NaN
467       2.000000e+05
468       8.000000e+04
469       1.400000e+05
470                NaN
471                NaN
472       9.000000e+09
473                NaN
474                NaN
475                NaN
476       4.500000e+03
477       2.000000e+05
478                NaN
479                NaN
480                NaN
481                NaN
482                NaN
483                NaN
484       6.000000e+03
485       9.300000e+04
486                NaN
487                NaN
488       6.000000e+06
489       1.350000e+05
490                NaN
491       5.500000e+04
492       1.650000e+05
493                NaN
494                NaN
495                NaN
496       1.000000e+05
497       8.400000e+05
498       1.020000e+05
499                NaN
500       4.000000e+06
501       6.500000e+02
502                NaN
503                NaN
504                NaN
505       4.000000e+04
506                NaN
507                NaN
508                NaN
509                NaN
510       1.700000e+05
511                NaN
512       4.000000e+04
513                NaN
514                NaN
515       1.360000e+05
516       4.500000e+04
517       3.000000e+03
518                NaN
519                NaN
520       1.500000e+05
521       5.000000e+04
522                NaN
523                NaN
524       4.300000e+04
525                NaN
526                NaN
527       3.000000e+05
528       1.750000e+05
529       6.500000e+05
530       8.000000e+04
531                NaN
532                NaN
533                NaN
534       3.120000e+04
535                NaN
536                NaN
537       5.200000e+04
538       1.300000e+05
539                NaN
540       8.400000e+04
541                NaN
542       3.600000e+04
543       1.500000e+05
544                NaN
545       4.000000e+05
546                NaN
547                NaN
548       1.100000e+06
549       1.600000e+05
550                NaN
551       7.800000e+04
552       1.100000e+05
553       1.440000e+05
554                NaN
555                NaN
556                NaN
557                NaN
558                NaN
559       3.900000e+04
560       1.000000e+05
561                NaN
562                NaN
563                NaN
564       6.200000e+04
565       1.000000e+05
566       2.200000e+05
567       2.000000e+04
568       2.200000e+05
569       5.700000e+04
570       2.500000e+05
571       3.000000e+05
572       1.400000e+05
573                NaN
574                NaN
575       1.800000e+05
576       4.000000e+04
577                NaN
578       5.900000e+04
579       1.500000e+05
580                NaN
581       8.200000e+04
582                NaN
583       6.500000e+04
584                NaN
585       1.000000e+05
586       4.400000e+04
587       1.500000e+05
588                NaN
589       1.500000e+05
590                NaN
591       9.000000e+04
592       1.500000e+05
593                NaN
594       4.320000e+05
595       7.050000e+04
596       1.200000e+05
597                NaN
598       1.400000e+04
599                NaN
600                NaN
601       2.700000e+04
602       6.600000e+03
603       5.300000e+04
604       6.000000e+04
605                NaN
606       1.850000e+05
607       7.900000e+04
608       5.500000e+04
609                NaN
610       8.000000e+04
611                NaN
612       8.500000e+04
613       5.000000e+05
614                NaN
615       6.300000e+04
616       1.400000e+05
617       5.900000e+04
618       6.700000e+04
619                NaN
620       1.200000e+05
621                NaN
622       9.100000e+04
623       1.000000e+11
624       2.050000e+05
625                NaN
626                NaN
627                NaN
628       8.750000e+04
629       1.000000e+05
630                NaN
631       1.150000e+05
632       4.100000e+04
633       1.010000e+05
634                NaN
635                NaN
636       3.000000e+05
637                NaN
638                NaN
639                NaN
640       1.500000e+05
641       8.300000e+04
642                NaN
643                NaN
644                NaN
645                NaN
646                NaN
647                NaN
648                NaN
649       8.400000e+04
650       8.100000e+04
651                NaN
652       1.900000e+05
653                NaN
654       2.500000e+04
655       3.500000e+04
656       5.000000e+04
657                NaN
658       1.400000e+05
659       1.020000e+04
660       5.000000e+04
661                NaN
662       1.500000e+05
663       3.000000e+04
664                NaN
665       4.000000e+06
666                NaN
667                NaN
668                NaN
669       1.180000e+05
670       1.500000e+05
671       8.725000e+04
672                NaN
673                NaN
674                NaN
675       5.200000e+04
676                NaN
677       4.000000e+04
678       4.000000e+05
679       5.300000e+04
680                NaN
681       8.500000e+04
682       5.000000e+06
683                NaN
684                NaN
685       1.240000e+05
686                NaN
687       5.400000e+04
688                NaN
689       8.500000e+04
690       1.200000e+05
691       4.100000e+04
692       8.000000e+04
693                NaN
694       5.800000e+03
695       3.600000e+06
696       2.000000e+05
697       0.000000e+00
698                NaN
699       1.300000e+05
700       2.500000e+05
701                NaN
702       2.050000e+05
703       2.500000e+05
704                NaN
705       2.500000e+05
706       1.200000e+04
707       8.000000e+06
708                NaN
709       6.500000e+04
710       3.900000e+04
711       3.000000e+04
712                NaN
713       2.570000e+05
714       1.630000e+05
715                NaN
716                NaN
717       7.400000e+05
718       2.000000e+05
719       1.000000e+05
720                NaN
721       3.000000e+05
722       8.000000e+05
723                NaN
724       6.200000e+04
725       4.500000e+04
726                NaN
727       4.400000e+04
728       2.600000e+04
729       2.000000e+05
730       1.050000e+05
731                NaN
732       2.640000e+05
733       1.000000e+06
734                NaN
735                NaN
736                NaN
737       4.800000e+04
738       7.000000e+04
739                NaN
740       1.500000e+05
741       1.000000e+05
742       5.000000e+04
743                NaN
744       8.500000e+04
745                NaN
746       1.680000e+05
747                NaN
748       7.500000e+04
749                NaN
750       1.600000e+06
751       4.020000e+05
752                NaN
753       1.276800e+05
754       3.274400e+04
755                NaN
756                NaN
757                NaN
758                NaN
759       7.500000e+04
760                NaN
761       1.750000e+05
762       3.952000e+04
763       5.380000e+04
764       1.200000e+05
765       9.000000e+04
766                NaN
767                NaN
768       8.000000e+04
769       1.200000e+05
770       2.600000e+04
771                NaN
772       6.750000e+03
773                NaN
774       1.200000e+05
775                NaN
776       7.900000e+04
777                NaN
778       1.200000e+05
779       1.280000e+05
780       2.400000e+05
781       1.630000e+05
782       7.320000e+04
783                NaN
784                NaN
785       6.000000e+04
786       8.000000e+04
787       6.600000e+04
788       7.800000e+04
789       7.200000e+04
790                NaN
791       2.750000e+04
792       1.500000e+05
793                NaN
794       1.700000e+05
795       1.500000e+05
796       1.560000e+04
797                NaN
798                NaN
799       4.300000e+04
800                NaN
801                NaN
802       5.000000e+04
803       5.800000e+04
804                NaN
805       1.450000e+05
806                NaN
807       9.200000e+04
808       6.300000e+04
809                NaN
810       1.181060e+05
811       2.000000e+05
812                NaN
813                NaN
814                NaN
815       3.000000e+04
816       1.100000e+05
817       8.000000e+05
818       7.260000e+04
819                NaN
820                NaN
821       1.500000e+05
822                NaN
823       2.150000e+05
824       1.450000e+05
825       3.500000e+06
826                NaN
827       7.000000e+04
828       1.000000e+06
829       1.950000e+05
830       1.650000e+05
831                NaN
832       3.400000e+04
833       1.400000e+06
834       3.600000e+06
835       2.400000e+04
836                NaN
837                NaN
838                NaN
839                NaN
840                NaN
841       1.270000e+05
842                NaN
843       9.800000e+04
844       9.000000e+04
845                NaN
846       5.000000e+04
847                NaN
848                NaN
849                NaN
850                NaN
851                NaN
852       1.750000e+05
853                NaN
854       1.590000e+05
855       1.550000e+05
856       1.000000e+05
857                NaN
858       6.000000e+04
859                NaN
860       2.110000e+05
861                NaN
862                NaN
863                NaN
864                NaN
865                NaN
866       7.200000e+04
867                NaN
868                NaN

In [75]:
df.head()

,ResponseId,MainBranch,Age,Employment,RemoteWork,Check,CodingActivities,EdLevel,LearnCode,LearnCodeOnline,TechDoc,YearsCode,YearsCodePro,DevType,OrgSize,PurchaseInfluence,BuyNewTool,BuildvsBuy,TechEndorse,Country,Currency,Salary,LanguageHaveWorkedWith,LanguageWantToWorkWith,LanguageAdmired,DatabaseHaveWorkedWith,DatabaseWantToWorkWith,DatabaseAdmired,PlatformHaveWorkedWith,PlatformWantToWorkWith,PlatformAdmired,WebframeHaveWorkedWith,WebframeWantToWorkWith,WebframeAdmired,EmbeddedHaveWorkedWith,EmbeddedWantToWorkWith,EmbeddedAdmired,MiscTechHaveWorkedWith,MiscTechWantToWorkWith,MiscTechAdmired,ToolsTechHaveWorkedWith,ToolsTechWantToWorkWith,ToolsTechAdmired,NEWCollabToolsHaveWorkedWith,NEWCollabToolsWantToWorkWith,NEWCollabToolsAdmired,OpSysPersonal use,OpSysProfessional use,OfficeStackAsyncHaveWorkedWith,OfficeStackAsyncWantToWorkWith,OfficeStackAsyncAdmired,OfficeStackSyncHaveWorkedWith,OfficeStackSyncWantToWorkWith,OfficeStackSyncAdmired,AISearchDevHaveWorkedWith,AISearchDevWantToWorkWith,AISearchDevAdmired,NEWSOSites,SOVisitFreq,SOAccount,SOPartFreq,SOHow,SOComm,AISelect,AISent,AIBen,AIAcc,AIComplex,AIToolCurrently Using,AIToolInterested in Using,AIToolNot interested in Using,AINextMuch more integrated,AINextNo change,AINextMore integrated,AINextLess integrated,AINextMuch less integrated,AIThreat,AIEthics,AIChallenges,TBranch,ICorPM,WorkExp,Knowledge_1,Knowledge_2,Knowledge_3,Knowledge_4,Knowledge_5,Knowledge_6,Knowledge_7,Knowledge_8,Knowledge_9,Frequency_1,Frequency_2,Frequency_3,TimeSearching,TimeAnswering,Frustration,ProfessionalTech,ProfessionalCloud,ProfessionalQuestion,Industry,JobSatPoints_1,JobSatPoints_4,JobSatPoints_5,JobSatPoints_6,JobSatPoints_7,JobSatPoints_8,JobSatPoints_9,JobSatPoints_10,JobSatPoints_11,SurveyLength,SurveyEase,ConvertedCompYearly,JobSat
0,1,I am a developer by profession,Under 18 years old,"Employed, full-time",Remote,Apples,Hobby,Primary/elementary school,Books / Physical media,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,United States of America,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,I have never visited Stack Overflow or the Sta...,NaN,NaN,NaN,NaN,NaN,Yes,Very favorable,Increase productivity,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,No,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,2,I am a developer by profession,35-44 years old,"Employed, full-time",Remote,Apples,Hobby;Contribute to open-source projects;Other...,"Bachelor’s degree (B.A., B.S., B.Eng., etc.)",Books / Physical media;Colleague;On the job tr...,Technical documentation;Blogs;Books;Written Tu...,API document(s) and/or SDK document(s);User gu...,20,17,"Developer, full-stack",NaN,NaN,NaN,NaN,NaN,United Kingdom of Great Britain and Northern I...,NaN,NaN,Bash/Shell (all shells);Go;HTML/CSS;Java;JavaS...,Bash/Shell (all shells);Go;HTML/CSS;Java;JavaS...,Bash/Shell (all shells);Go;HTML/CSS;Java;JavaS...,Dynamodb;MongoDB;PostgreSQL,PostgreSQL,PostgreSQL,Amazon Web Services (AWS);Heroku;Netlify,Amazon Web Services (AWS);Heroku;Netlify,Amazon Web Services (AWS);Heroku;Netlify,Express;Next.js;Node.js;React,Express;Htmx;Node.js;React;Remix,Express;Node.js;React,NaN,NaN,NaN,NaN,NaN,NaN,Docker;Homebrew;Kubernetes;npm;Vite;Webpack,Docker;Homebrew;Kubernetes;npm;Vite;Webpack,Docker;Homebrew;Kubernetes;npm;Vite;Webpack,PyCharm;Visual Studio Code;WebStorm,PyCharm;Visual Studio Code;WebStorm,PyCharm;Visual Studio Code;WebStorm,MacOS;Windows,MacOS,NaN,NaN,NaN,Microsoft Teams;Slack,Slack,Slack,NaN,NaN,NaN,Stack Overflow for Teams (private knowledge sh...,Multiple times per day,Yes,Multiple times per day,Quickly finding code solutions;Finding reliabl...,"Yes, definitely","No, and I don't plan to",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Yes,Individual contributor,17.0,Agree,Disagree,Agree,Agree,Agree,Neither agree nor disagree,Disagree,Agree,Agree,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,NaN,NaN,NaN,NaN
2,3,I am a developer by profession,45-54 years old,"Employed, full-time",Remote,Apples,Hobby;Contribute to open-source projects;Other...,"Master’s degree (M.A., M.S., M.Eng., MBA, etc.)",Books / Physical media;Colleague;On the job tr...,Technical documentation;Blogs;Books;Written Tu...,API document(s) and/or SDK document(s);User gu...,37,27,Developer Experience,NaN,NaN,NaN,NaN,NaN,United Kingdom of Great Britain and Northern I...,NaN,NaN,C#,C#,C#,Firebase Realtime Database,Firebase Realtime Database,Firebase Realtime Database,Google Cloud,Google Cloud,Google Cloud,ASP.NET CORE,ASP.NET CORE,ASP.NET CORE,Rasberry Pi,Rasberry Pi,Rasberry Pi,.NET (5+) ;.NET Framework (1.0 - 4.8);.NET MAUI,.NET (5+) ;.NET Framework (1.0 - 4.8);.NET MAUI,.NET (5+) ;.NET Framework (1.0 - 4.8);.NET MAUI,MSBuild,MSBuild,MSBuild,Visual Studio,Visual Studio,Visual Studio,Windows,Windows,NaN,NaN,NaN,Google Chat;Google Meet;Microsoft Teams;Zoom,Google Chat;Google Meet;Zoom,Google Chat;Google Meet;Zoom,NaN,NaN,NaN,Stack Overflow;Stack Exchange;Stack Overflow B...,Multiple times per day,Yes,Multiple times per day,Quickly finding code solutions;Finding reliabl...,"Yes, definitely","No, and I don't plan to",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,No,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Appropriate in length,Easy,NaN,NaN
3,4,I am learning to code,18-24 years old,"Student, full-time",NaN,Apples,NaN,Some college/university study without earning ...,"Other online resources (e.g., videos, blogs, f...",Stack Overflow;How-to videos;Interactive tutorial,NaN,4,NaN,"Developer, full-stack",NaN,NaN,NaN,NaN,NaN,Canada,NaN,NaN,C;C++;HTML/CSS;Java;JavaScript;PHP;PowerShell;...,HTML/CSS;Java;JavaScript;PowerShell;Python;SQL...,HTML/CSS;Java;JavaScript;PowerShell;Python;SQL...,MongoDB;MySQL;PostgreSQL;SQLite,MongoDB;MySQL;PostgreSQL,MongoDB;MySQL;PostgreSQL,Amazon Web Services (AWS);Fly.io;Heroku,Amazon Web Services (AWS);Vercel,Amazon Web Services (AWS),jQuery;Next.js;Node.js;React;WordPress,jQuery;Next.js;Node.js;React,jQuery;Next.js;Node.js;React,Rasberry Pi,NaN,NaN,NumPy;Pandas;Ruff;TensorFlow,NaN,NaN,Docker;npm;Pip,Docker;Kubernetes;npm,Docker;npm,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Stack Overflow,Daily or almost daily,No,NaN,Quickly finding code solutions,"No, not really",Yes,Very favorable,Increase productivity;Greater efficiency;Impro...,Somewhat trust,Bad at handling complex tasks,Learning about a codebase;Project planning;Wri...,Testing code;Committing and reviewing code;Pre...,NaN,Learning about a codebase;Project planning;Wri...,NaN,NaN,NaN,NaN,No,Circulating misinformation or disinformation;M...,Don’t trust the output or answers,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Too long,Easy,NaN,NaN
4,5,I am a developer by profession,18-24 years old,"Student, full-time",NaN,Apples,NaN,"Secondary school (e.g. American high school, G...","Other online resources (e.g., videos, blogs, f...",Technical documentation;Blogs;Written Tutorial...,API document(s) and/or SDK document(s);User gu...,9,NaN,"Developer, full-stack",NaN,NaN,NaN,NaN,NaN,Norway,NaN,NaN,C++;HTML/CSS;JavaScript;Lua;Python;Rust,C++;HTML/CSS;JavaScript;Lua;Python,C++;HTML/CSS;JavaScript;Lua;Python,PostgreSQL;SQLite,PostgreSQL;SQLite,PostgreSQL;SQLite,NaN,NaN,NaN,NaN,NaN,NaN,CMake;Cargo;Rasberry Pi,CMake;Rasberry Pi,CMake;Rasberry Pi,NaN,NaN,NaN,APT;Make;npm,APT;Make,APT;Make,Vim,Vim,Vim,Other (please specify):,NaN,GitHub Discussions;Markdown File;Obsidian;Stac...,GitHub Discussions;Markdown File;Obsidian,GitHub Discussions;Markdown File;Obsidian,Discord;Whatsapp,Discord;Whatsapp,Discord;Whatsapp,NaN,NaN,NaN,Stack Overflow for Teams (private knowledge sh...,Multiple times per day,Yes,Multiple times per day,Quickly finding code solutions;Engage with com...,"Yes, definitely","No, and I don't plan to",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Too short,Easy,NaN,NaN

In [76]:
schema_df.head()

,qid,qname,question,force_resp,type,selector
0,QID2,MainBranch,Which of the following options best describes ...,True,MC,SAVR
1,QID127,Age,What is your age?*,True,MC,SAVR
2,QID296,Employment,Which of the following best describes your cur...,True,MC,MAVR
3,QID308,RemoteWork,Which best describes your current work situation?,False,MC,SAVR
4,QID341,Check,Just checking to make sure you are paying atte...,True,MC,SAVR

In [80]:
schema_df.set_index("qname",inplace = True)

In [82]:
schema_df.reset_index(inplace = True)

In [84]:
df["SOAccount"] = df["SOAccount"].map({"Yes":True,"No":False,"NAN":"NAN"})

In [85]:
df.head()

,ResponseId,MainBranch,Age,Employment,RemoteWork,Check,CodingActivities,EdLevel,LearnCode,LearnCodeOnline,TechDoc,YearsCode,YearsCodePro,DevType,OrgSize,PurchaseInfluence,BuyNewTool,BuildvsBuy,TechEndorse,Country,Currency,Salary,LanguageHaveWorkedWith,LanguageWantToWorkWith,LanguageAdmired,DatabaseHaveWorkedWith,DatabaseWantToWorkWith,DatabaseAdmired,PlatformHaveWorkedWith,PlatformWantToWorkWith,PlatformAdmired,WebframeHaveWorkedWith,WebframeWantToWorkWith,WebframeAdmired,EmbeddedHaveWorkedWith,EmbeddedWantToWorkWith,EmbeddedAdmired,MiscTechHaveWorkedWith,MiscTechWantToWorkWith,MiscTechAdmired,ToolsTechHaveWorkedWith,ToolsTechWantToWorkWith,ToolsTechAdmired,NEWCollabToolsHaveWorkedWith,NEWCollabToolsWantToWorkWith,NEWCollabToolsAdmired,OpSysPersonal use,OpSysProfessional use,OfficeStackAsyncHaveWorkedWith,OfficeStackAsyncWantToWorkWith,OfficeStackAsyncAdmired,OfficeStackSyncHaveWorkedWith,OfficeStackSyncWantToWorkWith,OfficeStackSyncAdmired,AISearchDevHaveWorkedWith,AISearchDevWantToWorkWith,AISearchDevAdmired,NEWSOSites,SOVisitFreq,SOAccount,SOPartFreq,SOHow,SOComm,AISelect,AISent,AIBen,AIAcc,AIComplex,AIToolCurrently Using,AIToolInterested in Using,AIToolNot interested in Using,AINextMuch more integrated,AINextNo change,AINextMore integrated,AINextLess integrated,AINextMuch less integrated,AIThreat,AIEthics,AIChallenges,TBranch,ICorPM,WorkExp,Knowledge_1,Knowledge_2,Knowledge_3,Knowledge_4,Knowledge_5,Knowledge_6,Knowledge_7,Knowledge_8,Knowledge_9,Frequency_1,Frequency_2,Frequency_3,TimeSearching,TimeAnswering,Frustration,ProfessionalTech,ProfessionalCloud,ProfessionalQuestion,Industry,JobSatPoints_1,JobSatPoints_4,JobSatPoints_5,JobSatPoints_6,JobSatPoints_7,JobSatPoints_8,JobSatPoints_9,JobSatPoints_10,JobSatPoints_11,SurveyLength,SurveyEase,ConvertedCompYearly,JobSat
0,1,I am a developer by profession,Under 18 years old,"Employed, full-time",Remote,Apples,Hobby,Primary/elementary school,Books / Physical media,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,United States of America,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,I have never visited Stack Overflow or the Sta...,NaN,NaN,NaN,NaN,NaN,Yes,Very favorable,Increase productivity,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,No,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,2,I am a developer by profession,35-44 years old,"Employed, full-time",Remote,Apples,Hobby;Contribute to open-source projects;Other...,"Bachelor’s degree (B.A., B.S., B.Eng., etc.)",Books / Physical media;Colleague;On the job tr...,Technical documentation;Blogs;Books;Written Tu...,API document(s) and/or SDK document(s);User gu...,20,17,"Developer, full-stack",NaN,NaN,NaN,NaN,NaN,United Kingdom of Great Britain and Northern I...,NaN,NaN,Bash/Shell (all shells);Go;HTML/CSS;Java;JavaS...,Bash/Shell (all shells);Go;HTML/CSS;Java;JavaS...,Bash/Shell (all shells);Go;HTML/CSS;Java;JavaS...,Dynamodb;MongoDB;PostgreSQL,PostgreSQL,PostgreSQL,Amazon Web Services (AWS);Heroku;Netlify,Amazon Web Services (AWS);Heroku;Netlify,Amazon Web Services (AWS);Heroku;Netlify,Express;Next.js;Node.js;React,Express;Htmx;Node.js;React;Remix,Express;Node.js;React,NaN,NaN,NaN,NaN,NaN,NaN,Docker;Homebrew;Kubernetes;npm;Vite;Webpack,Docker;Homebrew;Kubernetes;npm;Vite;Webpack,Docker;Homebrew;Kubernetes;npm;Vite;Webpack,PyCharm;Visual Studio Code;WebStorm,PyCharm;Visual Studio Code;WebStorm,PyCharm;Visual Studio Code;WebStorm,MacOS;Windows,MacOS,NaN,NaN,NaN,Microsoft Teams;Slack,Slack,Slack,NaN,NaN,NaN,Stack Overflow for Teams (private knowledge sh...,Multiple times per day,True,Multiple times per day,Quickly finding code solutions;Finding reliabl...,"Yes, definitely","No, and I don't plan to",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Yes,Individual contributor,17.0,Agree,Disagree,Agree,Agree,Agree,Neither agree nor disagree,Disagree,Agree,Agree,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,NaN,NaN,NaN,NaN
2,3,I am a developer by profession,45-54 years old,"Employed, full-time",Remote,Apples,Hobby;Contribute to open-source projects;Other...,"Master’s degree (M.A., M.S., M.Eng., MBA, etc.)",Books / Physical media;Colleague;On the job tr...,Technical documentation;Blogs;Books;Written Tu...,API document(s) and/or SDK document(s);User gu...,37,27,Developer Experience,NaN,NaN,NaN,NaN,NaN,United Kingdom of Great Britain and Northern I...,NaN,NaN,C#,C#,C#,Firebase Realtime Database,Firebase Realtime Database,Firebase Realtime Database,Google Cloud,Google Cloud,Google Cloud,ASP.NET CORE,ASP.NET CORE,ASP.NET CORE,Rasberry Pi,Rasberry Pi,Rasberry Pi,.NET (5+) ;.NET Framework (1.0 - 4.8);.NET MAUI,.NET (5+) ;.NET Framework (1.0 - 4.8);.NET MAUI,.NET (5+) ;.NET Framework (1.0 - 4.8);.NET MAUI,MSBuild,MSBuild,MSBuild,Visual Studio,Visual Studio,Visual Studio,Windows,Windows,NaN,NaN,NaN,Google Chat;Google Meet;Microsoft Teams;Zoom,Google Chat;Google Meet;Zoom,Google Chat;Google Meet;Zoom,NaN,NaN,NaN,Stack Overflow;Stack Exchange;Stack Overflow B...,Multiple times per day,True,Multiple times per day,Quickly finding code solutions;Finding reliabl...,"Yes, definitely","No, and I don't plan to",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,No,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Appropriate in length,Easy,NaN,NaN
3,4,I am learning to code,18-24 years old,"Student, full-time",NaN,Apples,NaN,Some college/university study without earning ...,"Other online resources (e.g., videos, blogs, f...",Stack Overflow;How-to videos;Interactive tutorial,NaN,4,NaN,"Developer, full-stack",NaN,NaN,NaN,NaN,NaN,Canada,NaN,NaN,C;C++;HTML/CSS;Java;JavaScript;PHP;PowerShell;...,HTML/CSS;Java;JavaScript;PowerShell;Python;SQL...,HTML/CSS;Java;JavaScript;PowerShell;Python;SQL...,MongoDB;MySQL;PostgreSQL;SQLite,MongoDB;MySQL;PostgreSQL,MongoDB;MySQL;PostgreSQL,Amazon Web Services (AWS);Fly.io;Heroku,Amazon Web Services (AWS);Vercel,Amazon Web Services (AWS),jQuery;Next.js;Node.js;React;WordPress,jQuery;Next.js;Node.js;React,jQuery;Next.js;Node.js;React,Rasberry Pi,NaN,NaN,NumPy;Pandas;Ruff;TensorFlow,NaN,NaN,Docker;npm;Pip,Docker;Kubernetes;npm,Docker;npm,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Stack Overflow,Daily or almost daily,False,NaN,Quickly finding code solutions,"No, not really",Yes,Very favorable,Increase productivity;Greater efficiency;Impro...,Somewhat trust,Bad at handling complex tasks,Learning about a codebase;Project planning;Wri...,Testing code;Committing and reviewing code;Pre...,NaN,Learning about a codebase;Project planning;Wri...,NaN,NaN,NaN,NaN,No,Circulating misinformation or disinformation;M...,Don’t trust the output or answers,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Too long,Easy,NaN,NaN
4,5,I am a developer by profession,18-24 years old,"Student, full-time",NaN,Apples,NaN,"Secondary school (e.g. American high school, G...","Other online resources (e.g., videos, blogs, f...",Technical documentation;Blogs;Written Tutorial...,API document(s) and/or SDK document(s);User gu...,9,NaN,"Developer, full-stack",NaN,NaN,NaN,NaN,NaN,Norway,NaN,NaN,C++;HTML/CSS;JavaScript;Lua;Python;Rust,C++;HTML/CSS;JavaScript;Lua;Python,C++;HTML/CSS;JavaScript;Lua;Python,PostgreSQL;SQLite,PostgreSQL;SQLite,PostgreSQL;SQLite,NaN,NaN,NaN,NaN,NaN,NaN,CMake;Cargo;Rasberry Pi,CMake;Rasberry Pi,CMake;Rasberry Pi,NaN,NaN,NaN,APT;Make;npm,APT;Make,APT;Make,Vim,Vim,Vim,Other (please specify):,NaN,GitHub Discussions;Markdown File;Obsidian;Stac...,GitHub Discussions;Markdown File;Obsidian,GitHub Discussions;Markdown File;Obsidian,Discord;Whatsapp,Discord;Whatsapp,Discord;Whatsapp,NaN,NaN,NaN,Stack Overflow for Teams (private knowledge sh...,Multiple times per day,True,Multiple times per day,Quickly finding code solutions;Engage with com...,"Yes, definitely","No, and I don't plan to",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Too short,Easy,NaN,NaN